<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>transaction_Number</name>
   <tag></tag>
   <elementGuidId>defafad0-1f82-4868-802c-59327224b470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_EZ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_EZ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;40559348&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20a8349e-26ee-4219-9458-b91d556a80f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_EZ</value>
      <webElementGuid>a07718c4-545c-4975-ad44-24b3a48425d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_HeaderItem_0</value>
      <webElementGuid>509ed74f-b39c-44e6-8e08-d88526d28b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>e11214eb-16ca-462c-b18b-8dbb813886e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headerItemDisabled</value>
      <webElementGuid>031ce956-6ff5-4e65-a395-f8f8b5df5c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>40559348</value>
      <webElementGuid>1bee848e-bbe8-4f58-946e-3e7c947f0d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_EZ&quot;)</value>
      <webElementGuid>684c1788-a19f-4010-9ecc-1d0d0c4fcd84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_EZ']</value>
      <webElementGuid>5d0870b3-b50a-4afe-b504-d4c613533061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='isc_EY']/div</value>
      <webElementGuid>9ac8ca34-4eaf-4d12-aae2-fee375a7faf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[2]/following::div[9]</value>
      <webElementGuid>5c11a969-4567-4f8a-9690-36d6f30a1d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[2]/preceding::div[14]</value>
      <webElementGuid>cef7d2a0-0834-4004-af9a-a0175703ef30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Sale'])[1]/preceding::div[15]</value>
      <webElementGuid>672c5d44-1d77-41f6-b170-879f751278c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='40559348']/parent::*</value>
      <webElementGuid>7b2fab87-4a99-4806-a091-fc283c7f89f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/form/table/tbody/tr[2]/td/div</value>
      <webElementGuid>0f29c6c7-e8aa-45bc-a4b4-ea9583925911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_EZ' and (text() = '40559348' or . = '40559348')]</value>
      <webElementGuid>55e0a7e0-da8a-4aa2-ae26-22d2580ce064</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
