<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cement Australia Pty Limited (CEMENAUS)</name>
   <tag></tag>
   <elementGuidId>859d6420-1ab4-4df8-8daa-9fc2df42d4b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='isc_MHtable']/tbody/tr[3]/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.pickListCellSelected > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Cement Australia Pty Limited (CEMENAUS)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>130e54ce-5ab5-4ca5-9216-dcd58bc7478f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>8c0aabcd-1b3b-4025-acca-94cd2a577309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1700c76b-3925-4660-a15b-f563228acf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cement Australia Pty Limited (CEMENAUS)</value>
      <webElementGuid>a494c412-2023-469c-8edf-e9ae68fd803a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_MHtable&quot;)/tbody[1]/tr[3]/td[@class=&quot;pickListCellSelected&quot;]/div[1]</value>
      <webElementGuid>f9eedb7d-f5d9-4323-9ed7-2d8608040a35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_MHtable']/tbody/tr[3]/td/div</value>
      <webElementGuid>0e003911-b3cb-4205-ab4d-1c4e3ea47f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boral Cement Limited (BORALCEM)'])[1]/following::div[1]</value>
      <webElementGuid>ecb14772-9a0f-460c-b6b0-8c40a376d971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Etex Australia Pty Ltd Fibre Cement (ETEXAFC)'])[1]/preceding::div[1]</value>
      <webElementGuid>c910217d-3c8c-4778-9faf-e3b00c0ada0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cement Australia Pty Limited (CEMENAUS)']/parent::*</value>
      <webElementGuid>8a224682-c31f-4093-a7c9-87b593067889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/table/tbody/tr[3]/td/div</value>
      <webElementGuid>7daf0904-b391-4158-85f5-11ca371cd6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cement Australia Pty Limited (CEMENAUS)' or . = 'Cement Australia Pty Limited (CEMENAUS)')]</value>
      <webElementGuid>e3da6d0e-2ae8-4efe-8973-d827e595aee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
