<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HomePurchase Orders</name>
   <tag></tag>
   <elementGuidId>e249bfeb-92d1-4e88-933d-becfae2d40ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_X']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_X</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;HomePurchase Orders&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f2fdca7-7ec1-421a-9cf2-550b1a5cf8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_X</value>
      <webElementGuid>b54d836f-bd5b-472d-88d1-c50ea9b6706a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventproxy</name>
      <type>Main</type>
      <value>AppTabSet_Main_tabBar</value>
      <webElementGuid>e46a4730-e1c5-4ce9-acbd-8e0d54ac6035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabBarTop</value>
      <webElementGuid>cf86005b-671e-49c7-a83e-86785724b776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onscroll</name>
      <type>Main</type>
      <value>return AppTabSet_Main_tabBar.$lh()</value>
      <webElementGuid>d59c3401-0580-4c00-82ca-852d4dfa1192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tablist</value>
      <webElementGuid>f9c83f66-90bf-4cb3-a2ef-f9da2208c9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   HomePurchase Orders</value>
      <webElementGuid>e8c5d99e-a353-4910-acd6-ce11fe764c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_X&quot;)</value>
      <webElementGuid>4e4c323e-880b-4b1f-8e7a-51991cf26d09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_X']</value>
      <webElementGuid>49d1c7bd-8a9c-48dc-8d42-d1e13c437691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_W']/div</value>
      <webElementGuid>66cd646c-822a-4e88-9823-2c07c76a4230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kino Rafael Manalo (manaki)'])[1]/following::div[3]</value>
      <webElementGuid>3b4ced37-0e8c-4dee-b829-d8347f6e3b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Device:'])[1]/following::div[7]</value>
      <webElementGuid>6c420201-a08a-43b2-a7a6-ec17b63e557f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div</value>
      <webElementGuid>3efa9b3a-39fd-4402-bae4-1be376ac12da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_X' and (text() = '   HomePurchase Orders' or . = '   HomePurchase Orders')]</value>
      <webElementGuid>994a4a20-95d6-4213-a42c-e6546e64e8e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
