<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Date Required_isc_G6</name>
   <tag></tag>
   <elementGuidId>141f5413-9b69-45b4-9869-61e3a3c547aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'http://frameworks.cairnshardware.com.au:8080/FWDemo2/frameworks/sc/skins/Frameworks7/images/custom/buttons/calendar.png')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_G6</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//img[@src = 'http://frameworks.cairnshardware.com.au:8080/FWDemo2/frameworks/sc/skins/Frameworks7/images/custom/buttons/calendar.png' and @height = '22' and @align = 'absmiddle' and @border = '0' and @suppress = 'TRUE' and @draggable = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;New Purchase Order&quot;i >> internal:label=&quot;Show Date Chooser&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87145f64-87f8-45bb-9d97-c6a3873e7b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://frameworks.cairnshardware.com.au:8080/FWDemo2/frameworks/sc/skins/Frameworks7/images/custom/buttons/calendar.png</value>
      <webElementGuid>5ef0c39f-cbf9-474d-9487-1dee88e61e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>1edbcdb5-365a-47a0-a188-e00157c071b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>e7530da6-5b98-4e2a-8aec-318c2e035b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>absmiddle</value>
      <webElementGuid>6752fbd5-4720-4c7c-b5ab-caaf64ff7ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_G6</value>
      <webElementGuid>e5c2e313-48cb-433e-8c90-d68e753ebf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e69fb25e-6c35-4906-b4dd-aa4d54aa1958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>suppress</name>
      <type>Main</type>
      <value>TRUE</value>
      <webElementGuid>6de76656-aeb7-44b7-a532-8baa49d44d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>79da38cf-826d-474e-bb52-964f1bfd5d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_G6&quot;)</value>
      <webElementGuid>13729a98-7805-4158-a275-f3f19174c678</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='isc_G6']</value>
      <webElementGuid>77c3bda0-67ef-4513-bbae-31ad9ad7afdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='isc_G5']/img</value>
      <webElementGuid>31fe3267-9b00-4921-b7ee-f7485754f8ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'http://frameworks.cairnshardware.com.au:8080/FWDemo2/frameworks/sc/skins/Frameworks7/images/custom/buttons/calendar.png')])[2]</value>
      <webElementGuid>743ec8d9-ec87-44d5-92ec-95b3c7595b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/span/img</value>
      <webElementGuid>f7523ea0-0d01-4fe4-942f-5a64df267648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://frameworks.cairnshardware.com.au:8080/FWDemo2/frameworks/sc/skins/Frameworks7/images/custom/buttons/calendar.png' and @id = 'isc_G6']</value>
      <webElementGuid>c34ff454-d9fa-4177-aa10-15bbd4ec5d93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
