<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Credit Notes</name>
   <tag></tag>
   <elementGuidId>8a320e81-7d26-4773-9c9f-9e85b274d782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_TreeGrid_0_valueCell4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='isc_TreeGrid_0_valueCell4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Credit Notes&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2009a712-7505-4c13-90a6-75b98227f1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_TreeGrid_0_valueCell4</value>
      <webElementGuid>266ce92b-ed2d-4936-bb1a-17acc0cba320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>treeTallCellSelectedOver</value>
      <webElementGuid>9fad9cc1-15f4-4099-a029-b64ce5a33d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Credit Notes</value>
      <webElementGuid>73f82e59-711c-43a1-a8b6-6570ef3fde97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_TreeGrid_0_valueCell4&quot;)</value>
      <webElementGuid>4af4f682-acc7-40e3-97bd-6e31e8d2ca2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_TreeGrid_0_valueCell4']</value>
      <webElementGuid>e3c62445-6fa1-49a5-be71-d0da8c2b524a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_7Btable']/tbody/tr[5]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>8554ee92-429d-4721-8801-2becb9de56d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Orders'])[1]/following::td[4]</value>
      <webElementGuid>fdf4926e-5f27-437d-83d6-f683c48b541b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Point Of Sale'])[1]/following::td[8]</value>
      <webElementGuid>6d9cc1e4-02cf-4cfb-9de1-00633e84eb86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Picking Dashboard'])[1]/preceding::td[3]</value>
      <webElementGuid>6aa6124f-080e-4264-9749-6cb0db616d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print Picking Slips'])[1]/preceding::td[7]</value>
      <webElementGuid>d8832ae3-b2f5-48f4-beff-47f5360c1859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Credit Notes']/parent::*</value>
      <webElementGuid>77f91855-123a-478d-a97c-c88ff93795e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>79e06388-b09b-40b6-b223-c97c5b1bbf97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_TreeGrid_0_valueCell4' and (text() = 'Credit Notes' or . = 'Credit Notes')]</value>
      <webElementGuid>142d3b10-4ec8-4462-96ab-285c52d40b62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
