<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3250</name>
   <tag></tag>
   <elementGuidId>2b2ace27-f50f-4f48-93b9-025aecf60d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.cellOverDark > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='3250']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;3250&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2746af9-1efb-49c7-a481-cfa3eea0c955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void</value>
      <webElementGuid>37ab8ae9-c4c8-4a45-bfb7-3d93208dfb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>javascript</value>
      <webElementGuid>525e1d9b-4982-491b-ab1a-fc5f0a7eae58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.productGroupFind_results_ListGrid1) return productGroupFind_results_ListGrid1.$30i(event,5,0);</value>
      <webElementGuid>6c6ab654-52bf-4f6b-b4a1-c721c2ce6070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3250</value>
      <webElementGuid>4fed2903-8234-4ad1-afc0-21771d75b0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1H3table&quot;)/tbody[1]/tr[6]/td[@class=&quot;cellOverDark&quot;]/div[1]/a[1]</value>
      <webElementGuid>5cd0bd04-deaf-4933-87ac-13cbda4a4723</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='if(window.productGroupFind_results_ListGrid1) return productGroupFind_results_ListGrid1.$30i(event,5,0);']</value>
      <webElementGuid>ea3a5491-b1a6-475d-ae0b-4b5e6b7b9687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_1H3table']/tbody/tr[6]/td/div/a</value>
      <webElementGuid>8f82dfa6-604a-4579-bc41-f4b3d0956caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'3250')]</value>
      <webElementGuid>03e0833a-2c5d-4b31-8a4f-40ca0d18e33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smart Home Automation'])[1]/following::a[1]</value>
      <webElementGuid>57ee982f-ceb6-47f8-939a-77e0f7b92b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Door &amp; Window Hardware'])[1]/following::a[2]</value>
      <webElementGuid>76283084-c062-49a4-a637-14c173198921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools &amp; Safety'])[1]/preceding::a[1]</value>
      <webElementGuid>45f94479-36be-45df-9e92-3b4e84fe627c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paint &amp; Accessories'])[1]/preceding::a[2]</value>
      <webElementGuid>1f8851db-a33a-4c29-952e-8bd7006d3c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3250']/parent::*</value>
      <webElementGuid>e355e2d9-b2e5-4f6c-9c39-48b0d2c33d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void')])[13]</value>
      <webElementGuid>41e0be48-e735-408d-bebc-3c9c04361b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/a</value>
      <webElementGuid>f20284fa-9122-4e84-96f2-713299d630a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void' and (text() = '3250' or . = '3250')]</value>
      <webElementGuid>86012bd9-36b8-48f9-afce-87d6c47982d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
