<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SourceRow2</name>
   <tag></tag>
   <elementGuidId>49a7dd21-c93a-4091-9dfe-9e8fce3fdb6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/table/tbody/tr[2]/td[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_26Stable > tbody > tr:nth-child(2) > td:nth-child(6) > div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a0d08b90-a90a-4381-acf7-0c2f2f3e30e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>f03f1afc-70e9-4dfc-a4d3-979ef21046ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>462fe45b-1ba4-4158-983b-ab21f03fed16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>b279fff8-618e-46d1-9a46-6cec4368b401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_26Stable&quot;)/tbody[1]/tr[2]/td[@class=&quot;treeTallCellSelectedOver&quot;]/div[1]</value>
      <webElementGuid>cbbbc76d-60ad-45a3-8769-dc38360b9685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_26Stable']/tbody/tr[2]/td[6]/div</value>
      <webElementGuid>112b548a-e928-46aa-8379-1d8d3a44807a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOT Stocked'])[1]/following::div[2]</value>
      <webElementGuid>a11462ed-1f01-45a0-b42e-d6f23c1bb679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZZ2281338910'])[2]/following::div[4]</value>
      <webElementGuid>e7b700a3-1b6e-4b24-a5be-781e28611595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ea'])[2]/preceding::div[4]</value>
      <webElementGuid>4e6f6bcf-ed1d-4bfb-ac49-eb7fea7368ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$75.00'])[1]/preceding::div[11]</value>
      <webElementGuid>1c6304e1-9059-4449-b5c4-cb23bc42af5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[2]/td[6]/div</value>
      <webElementGuid>7a00013b-12ed-4912-bd60-b2ac369cf106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>d9c516c2-aad4-40de-953d-bd3f7055f449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
