<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ResumeSale_1</name>
   <tag></tag>
   <elementGuidId>b7b06d6b-8d5c-4284-8532-fede678219b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_LQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_LQ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Resume Sale&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11a6076f-bbd6-42db-9746-acfe2e610432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_LQ</value>
      <webElementGuid>67769358-7e32-47fd-803f-7f8af8c914ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>561b86b2-927f-493f-8f58-a1e2574c0fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ResumeSale</value>
      <webElementGuid>db1b0af8-2b21-4211-a18e-7cfb7a41fc4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_LQ&quot;)</value>
      <webElementGuid>495f8113-cacb-4048-8d9d-cd03367bfb7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_LQ']</value>
      <webElementGuid>06d859d2-24de-4f4e-bf5c-12a2c499921c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_L9']/table/tbody/tr/td/div</value>
      <webElementGuid>9ddb2232-ad9e-454b-91bc-72656a1b3127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reprice'])[1]/following::div[2]</value>
      <webElementGuid>553ec20e-e20a-47d4-aa14-3b713e5c82ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CustomerPickup'])[1]/following::div[4]</value>
      <webElementGuid>3a894f7a-1dd1-4977-91cc-011b0f1b8351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CreateOrder'])[1]/preceding::div[1]</value>
      <webElementGuid>fece2c6a-d456-42d1-96c4-675964f61ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CreateQuote'])[1]/preceding::div[3]</value>
      <webElementGuid>e33cb8d6-daea-49e9-83d5-7ce160b6720b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resume']/parent::*</value>
      <webElementGuid>2695aa11-2515-45e7-bf6d-8a54487b89a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/div/div/div[2]/div/div[4]/table/tbody/tr/td/div</value>
      <webElementGuid>c9b442c1-8f12-4e5a-a022-c73df1b59a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_LQ' and (text() = 'ResumeSale' or . = 'ResumeSale')]</value>
      <webElementGuid>cabf5a5c-90d1-45a4-b6a1-2e9eca3d51df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_1AP']</value>
      <webElementGuid>16688f69-e6f4-43b6-8916-cb5c4f165520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_1A8']/table/tbody/tr/td/div</value>
      <webElementGuid>83ea0a5a-5d85-44f0-9966-9c2a40985264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_1AP' and (text() = 'ResumeSale' or . = 'ResumeSale')]</value>
      <webElementGuid>5c99d2dc-c750-4454-9db3-6da50cf01ad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
