<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Payment History</name>
   <tag></tag>
   <elementGuidId>c3c57ff5-4777-472a-a5b0-904d446cfb92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_CZ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_CZ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Payment History&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>914805e2-cdcf-40c0-a97a-98f287d5382f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_CZ</value>
      <webElementGuid>183b64fa-cbe2-45e6-b275-abd0823ff302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>1e9fecfd-3d2f-4807-9ae2-0ea7fc71f9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment History</value>
      <webElementGuid>638d2e01-6c46-4967-8ff8-77a617096dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_CZ&quot;)</value>
      <webElementGuid>a0cfa922-ee9d-4fa8-ac09-d973ec3a9365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_CZ']</value>
      <webElementGuid>946fcad6-ecb1-4d52-be53-2731d1a4b428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_D0']/table/tbody/tr/td/div</value>
      <webElementGuid>afc96365-bce5-4076-a478-7f38203bcb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales History'])[1]/following::div[2]</value>
      <webElementGuid>b5d45e24-6711-41bb-a9ed-edaf30d5ad78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Information'])[1]/following::div[4]</value>
      <webElementGuid>1c49fd9a-3b0c-4829-a440-4f822deae016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Settings'])[1]/preceding::div[1]</value>
      <webElementGuid>492db43f-0dca-4093-82ff-ff7754dc1ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contracts'])[1]/preceding::div[3]</value>
      <webElementGuid>4710df1d-5294-4c79-8dd8-4d4f03ddc8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payment History']/parent::*</value>
      <webElementGuid>c61219d4-bdf9-4663-8a93-36e5a7fec582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/table/tbody/tr/td/div</value>
      <webElementGuid>9cfde5a3-3def-46e0-b458-5841633566dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_CZ' and (text() = 'Payment History' or . = 'Payment History')]</value>
      <webElementGuid>925821c0-195f-4ee0-92cb-6735fae4bdd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
