<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Charge</name>
   <tag></tag>
   <elementGuidId>e9a3cfa7-4cee-48f5-9e99-d4ff36e48c7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_XO</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'Charge' or . = 'Charge')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Charge']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Charge&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09a1bff2-74ac-4aad-8a64-c34a01fc9840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_XO</value>
      <webElementGuid>17ff2bf0-0fca-47d6-90a0-b7fbe095d279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f306e5d5-fad2-44ed-857e-7d9445025579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Charge</value>
      <webElementGuid>1c6be8aa-dc56-4c8c-9726-b9549ef41c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_XO&quot;)</value>
      <webElementGuid>74c19896-8c4c-432c-8266-854d7547fe27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_XO']</value>
      <webElementGuid>c721367f-998b-4486-a28c-4a29df00acec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_XP']/table/tbody/tr/td/div</value>
      <webElementGuid>174451a9-a7e4-4f13-81bc-28be40cef956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[2]/following::div[2]</value>
      <webElementGuid>5e838611-d23b-4daa-bf6e-5a2231318589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ON ACCOUNT'])[1]/following::div[2]</value>
      <webElementGuid>651e88bd-932d-41ff-b78f-fd3a2855ad3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Till No.'])[1]/preceding::div[1]</value>
      <webElementGuid>1d5102de-8ab7-4611-970d-53c291881ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Session'])[1]/preceding::div[5]</value>
      <webElementGuid>f80b9032-1251-4c39-aaf8-98e4e4059dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Charge']/parent::*</value>
      <webElementGuid>983105ad-1b97-447f-ad00-2309630adf46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>d1303644-5b27-49a6-936d-bc8fee1e3e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_XO' and (text() = 'Charge' or . = 'Charge')]</value>
      <webElementGuid>5b54713f-da19-4267-81a6-f0a6c18f4e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_UW']</value>
      <webElementGuid>3d477718-9b23-4bb4-8a9a-29fde2f96086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_UX']/table/tbody/tr/td/div</value>
      <webElementGuid>829f68e5-9e2b-49ae-bb8b-215bc9d2ac14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_UW' and (text() = 'Charge' or . = 'Charge')]</value>
      <webElementGuid>efadde65-7cfd-4918-9c0b-024faaf6e4f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
