<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_E-BEAM F17 LVL 120 X 45 H3 JD3 PER LM</name>
   <tag></tag>
   <elementGuidId>631da82f-a579-4eeb-8930-55c019d3ce63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_F3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_F3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;E-BEAM+ F17 LVL 120 X 45 H3 JD3 PER LM **&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9583ec6-f9a4-4445-8abd-3e6f6cbb97fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_F3</value>
      <webElementGuid>7d0b9860-5f85-40e2-8e56-97804c724bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_StaticTextItem_13</value>
      <webElementGuid>0ee399f1-7ca0-4244-9ae2-f4707bbb78e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>ebc455b8-3f5c-4768-9d9d-cb9290ae4cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>staticTextItem</value>
      <webElementGuid>a5b2652a-b72f-498e-872a-976236e3ff45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-BEAM+ F17 LVL 120 X 45 H3 JD3 PER LM **  </value>
      <webElementGuid>cfacc682-6d8f-47c5-8e02-b40e4035425f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_F3&quot;)</value>
      <webElementGuid>967135fe-e836-40dd-9a79-e70a01fdf882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_F3']</value>
      <webElementGuid>4552dfb7-9685-4487-952c-3a9a3b5b4a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='isc_F2']/div</value>
      <webElementGuid>65df3c99-0e10-498f-a5da-ac348580ca88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i'])[1]/following::div[4]</value>
      <webElementGuid>ad5a3d88-3433-4bac-82a6-5aaf7805597b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/preceding::div[1]</value>
      <webElementGuid>03dded2c-3d1c-40cb-8ad5-1947a512c6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an item to open'])[1]/preceding::div[23]</value>
      <webElementGuid>d4079cd4-b0bb-4c02-b291-14e3b7c41880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='E-BEAM+ F17 LVL 120 X 45 H3 JD3 PER LM **']/parent::*</value>
      <webElementGuid>f384ff4e-e020-4f3b-a9cb-eeb0934e6705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/table/tbody/tr[3]/td[2]/div</value>
      <webElementGuid>88c340d2-dbea-4269-be5f-f76d6026499d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_F3' and (text() = 'E-BEAM+ F17 LVL 120 X 45 H3 JD3 PER LM **  ' or . = 'E-BEAM+ F17 LVL 120 X 45 H3 JD3 PER LM **  ')]</value>
      <webElementGuid>93c09300-5601-4422-b360-33f4ebf6829a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
