<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stock Return</name>
   <tag></tag>
   <elementGuidId>bafd2968-f6a6-4871-8214-f6e2c6d9bc07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.pickListCellSelectedDark > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Stock Return' or . = 'Stock Return')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_NY >> internal:text=&quot;Stock Return&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de4d7842-8deb-4b46-9eef-9c2c04aeb0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>f27c42ac-cd40-464a-8932-9e3560377bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>794fef55-1570-4f4e-993b-21ee8016b4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stock Return</value>
      <webElementGuid>acbdb6c2-3396-4e05-a6c6-aa76e40b9881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_O0table&quot;)/tbody[1]/tr[2]/td[@class=&quot;pickListCellSelectedDark&quot;]/div[1]</value>
      <webElementGuid>ffb3acbd-a622-42fa-9d3c-c0e84aad8d20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_O0table']/tbody/tr[2]/td/div</value>
      <webElementGuid>ac473c33-d506-46ff-a14f-10b77ab58374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;Select a Value>'])[1]/following::div[1]</value>
      <webElementGuid>d06b5f39-b874-48e5-b00c-c4fe93dc5511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[14]</value>
      <webElementGuid>af91a6f4-18c1-42c5-8236-a570a0fdda9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overcharge'])[1]/preceding::div[1]</value>
      <webElementGuid>064342ca-55dc-4240-8ad9-20b9f18d4676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/table/tbody/tr[2]/td/div</value>
      <webElementGuid>a2ff3b9c-dc99-4bd8-ad20-ebaa30b4e59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Stock Return' or . = 'Stock Return')]</value>
      <webElementGuid>46dbdc4e-0bc4-4f79-bcd8-6c706eccdd64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
