<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_ProductQuantityQty UOMSell PriceDisc _b0a466</name>
   <tag></tag>
   <elementGuidId>ff9e3c82-bf24-41b1-a761-619a7a6f4642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_E6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='isc_E6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>table >> internal:has-text=&quot;ProductQuantityQty UOMSell PriceDisc %CEMENT GP 20KG NORTHERN CEMENT Comments&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
      <webElementGuid>638a7a2a-ab5b-41da-a505-6fa620d7da4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>59bbba38-3a65-4c5f-8ac9-f8e036d63700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_E6</value>
      <webElementGuid>abbef796-4d9c-433a-a78d-f112a9a263dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellspacing</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>55998eda-fd66-4963-9425-d70b78a9f484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellpadding</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ee922003-58c2-4e01-b67d-d1c8fb209524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3f2a225d-73f2-42ad-9348-26e5f8b3d2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProductQuantityQty UOMSell PriceDisc %CEMENT GP 20KG NORTHERN CEMENT  Comments         </value>
      <webElementGuid>f9647edb-5e68-4c70-9ff7-2578ad8b4be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_E6&quot;)</value>
      <webElementGuid>d0974a48-b99f-46f3-9105-e8a9e45a10be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//table[@id='isc_E6']</value>
      <webElementGuid>0eeaded4-2249-470f-8f06-64412cae5e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='isc_E5']/table</value>
      <webElementGuid>5e6eba00-98c6-4f3e-905e-92e50a22fdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No products added.'])[1]/following::table[2]</value>
      <webElementGuid>cbf03073-83e7-4e9e-bde5-c6545c893502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LinePrice'])[1]/following::table[6]</value>
      <webElementGuid>8d32fc3f-d88b-4b09-a28b-b43ad2b64799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/div/div/div[2]/div/form/table</value>
      <webElementGuid>555b15e9-8cd2-447e-abf1-3a8c1e1374aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//table[@id = 'isc_E6' and (text() = 'ProductQuantityQty UOMSell PriceDisc %CEMENT GP 20KG NORTHERN CEMENT  Comments         ' or . = 'ProductQuantityQty UOMSell PriceDisc %CEMENT GP 20KG NORTHERN CEMENT  Comments         ')]</value>
      <webElementGuid>8e3b56af-cb90-4819-a764-6d63addbb3a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
