<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td</name>
   <tag></tag>
   <elementGuidId>d6050cc6-c38f-4a3e-9667-a761c16317f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_GN > table > tbody > tr > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_GN']/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_GN td</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5a6bc21c-5e8a-4ec0-ac26-6d1adb35ed8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>6b7651f0-1702-4818-964b-283aff52dc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>642a4d54-86e0-4e7e-bd45-174d582646c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_GN&quot;)/table[1]/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>0fade0e1-35db-4d6d-9614-5f749ec12654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_GN']/table/tbody/tr/td</value>
      <webElementGuid>57dd0973-a1ad-48f0-9faf-1bfbfcddaf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/following::td[19]</value>
      <webElementGuid>b3aefac6-bf53-4bf7-b4ce-6f60e25fca87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i'])[1]/following::td[25]</value>
      <webElementGuid>a404c558-3925-45cf-88c5-b030bc29da2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an item to open'])[1]/preceding::td[7]</value>
      <webElementGuid>77fffe4f-1d34-487b-b4db-19d755c409a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/preceding::td[12]</value>
      <webElementGuid>4a5218a3-ee15-4356-b8b6-aae3b0ae8556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/table/tbody/tr/td</value>
      <webElementGuid>f36d75c3-b323-46d8-8ae6-3df6238fd034</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
