<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Close (O)</name>
   <tag></tag>
   <elementGuidId>4f6da1ea-7dcc-4da2-8f9e-8794ddb882aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.buttonNegativeActionOver</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_86']/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close (O)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0eea9b7d-8f6a-4910-ab97-b86efcc46a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nowrap</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>415b173d-9a2b-4e91-99e9-a2d8d2dc1f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonNegativeActionOver</value>
      <webElementGuid>1289c4c3-586b-4a92-b724-ad33943fbc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>d31ee4ca-5fcc-4b42-a4ad-46bba22d92a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>2fd030b1-fcea-4204-86e5-b1d9f13b5e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>PointOfSaleMain_CRUD_Close.$47()</value>
      <webElementGuid>fdd86b86-34a8-46f3-8a3b-43d443fc234e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close (O)</value>
      <webElementGuid>d5201321-e505-49a4-9538-949c0142ba38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_86&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;buttonNegativeActionOver&quot;]</value>
      <webElementGuid>3fa7da3d-9f14-4452-8bf4-bbcb5352c55b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_86']/table/tbody/tr/td</value>
      <webElementGuid>3e286302-a39f-4bbb-b7cf-b9f51ff11656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[1]/following::td[1]</value>
      <webElementGuid>fef92ee6-323b-4bd6-a664-6a9fcdaac3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]/div/table/tbody/tr/td</value>
      <webElementGuid>6a46ba19-128d-4b2c-9d44-85bf3a35ed8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Close (O)' or . = 'Close (O)')]</value>
      <webElementGuid>87aeace9-1c58-437c-8766-b30ff81bf075</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
