<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Follow-up Date_isc_IP</name>
   <tag></tag>
   <elementGuidId>722f1a7c-afa8-45dd-ba09-2c931abf9fbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'http://frameworks.dahlsens.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks7/images/custom/buttons/calendar.png')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_IP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Follow-up Date Show Date Chooser&quot;i] >> internal:label=&quot;Show Date Chooser&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1dad2fc6-c147-4bd6-80cc-88a3dffaed9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://frameworks.dahlsens.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks7/images/custom/buttons/calendar.png</value>
      <webElementGuid>da4c50b2-aafb-4151-8c01-8b6277084434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>0fce4fe4-0154-43b9-b51a-17daa0b27ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>a6c9bc9d-9569-4351-baa8-8c63f2fe0dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>absmiddle</value>
      <webElementGuid>b72fdf4b-ff29-444b-9635-30353da9d262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_IP</value>
      <webElementGuid>06010172-9a61-4bf2-aafd-66b3e581caa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e73a4ff7-8756-4493-a63c-8c35c2b15b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>suppress</name>
      <type>Main</type>
      <value>TRUE</value>
      <webElementGuid>cc9de5ab-01b3-4223-a1bf-e6fad034ee92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>553642ff-e72a-4615-b684-b09211ad5190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_IP&quot;)</value>
      <webElementGuid>cb2fc4a2-6fe1-4290-96eb-4d1e4bc36c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='isc_IP']</value>
      <webElementGuid>48e304ea-ddd2-47f7-9fe8-f1fcbafafba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='isc_IO']/img</value>
      <webElementGuid>a7e5ec68-6a4f-4be2-860f-f21464bf0826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'http://frameworks.dahlsens.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks7/images/custom/buttons/calendar.png')])[2]</value>
      <webElementGuid>506d39c1-fcca-4de1-bd21-65874ad39ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/span/img</value>
      <webElementGuid>c5941d4b-4ef3-4e36-ae0e-9486835d1129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://frameworks.dahlsens.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks7/images/custom/buttons/calendar.png' and @id = 'isc_IP']</value>
      <webElementGuid>9c028e2b-6e8c-4fd1-8f82-3d1daf00c9f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
