<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QLD - Queensland</name>
   <tag></tag>
   <elementGuidId>97ab6099-f847-448b-aed0-ce4e67320c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='QLD - Queensland']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_WOtable > tbody > tr > td.pickListCellSelected > div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'QLD - Queensland' or . = 'QLD - Queensland')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;QLD - Queensland&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a38b1281-42b9-49f3-845c-9312a99a3650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>9a8505be-bb25-436a-82af-7ed1e52c10b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ce50585-00f8-421c-9541-f09e107556ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QLD - Queensland</value>
      <webElementGuid>3ed3eec0-e2b7-433e-b129-e3f7adc222c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_WOtable&quot;)/tbody[1]/tr[1]/td[@class=&quot;pickListCellSelected&quot;]/div[1]</value>
      <webElementGuid>a1c0f445-f33f-444c-a1cf-bdd863c524d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_WOtable']/tbody/tr/td/div</value>
      <webElementGuid>678e09b2-7812-4e99-9168-28e80a3ce8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a new customer.'])[1]/following::div[7]</value>
      <webElementGuid>c2c84407-e6e2-49a8-be76-c73a31c053e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Hold'])[1]/following::div[12]</value>
      <webElementGuid>05e27567-9fad-4d37-bd51-62d2334dc57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QLD - Queensland']/parent::*</value>
      <webElementGuid>33d45b5e-6e85-4ef6-bbd7-58172618b2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>84a0b55b-e26e-4e0f-8540-aead21b821a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'QLD - Queensland' or . = 'QLD - Queensland')]</value>
      <webElementGuid>c034c760-0e14-46a4-9bdc-7d6f1666765c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_WNtable']/tbody/tr/td/div</value>
      <webElementGuid>c615c28c-d64d-49ff-9785-fb839bcad1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suburb cannot be blank'])[1]/following::div[6]</value>
      <webElementGuid>c4f47d1d-6bd8-42c2-a98a-0acb819b4d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Hold'])[1]/following::div[11]</value>
      <webElementGuid>2933e420-aa8c-4316-aa9c-3dc12ad887c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
