<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_501 - DEMONSTRATION BRANCH 501_1</name>
   <tag></tag>
   <elementGuidId>8db29892-684d-4c58-86f0-c8940e5d8390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'isc_G7' and (text() = '501 - DEMONSTRATION BRANCH 501' or . = '501 - DEMONSTRATION BRANCH 501')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_G7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;501 - DEMONSTRATION BRANCH 501&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c25bca1-5251-4877-8738-926ad0b584fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_G7</value>
      <webElementGuid>819d3a89-b3b2-4353-a78b-740046e3583e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_SelectItem_5</value>
      <webElementGuid>2924f372-795c-4618-9db4-7cb9e4a7a8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>577a10f9-05f3-493a-9794-d3530c0df23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectItemTextFocused</value>
      <webElementGuid>c7cd9e6c-fc77-4301-a477-71b86199df48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4056</value>
      <webElementGuid>7dd21959-7b30-4246-a284-099d656c1a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5b55f8b3-68e7-4a0e-aac3-b5adcf28309a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>501 - DEMONSTRATION BRANCH 501</value>
      <webElementGuid>4f1e79e6-aa19-49c7-8fd9-32e5fc1ad628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_G7&quot;)</value>
      <webElementGuid>58b7d20c-2520-4d2b-b4a1-424829eaac00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_G7']</value>
      <webElementGuid>16ba4354-5e46-4010-8243-f64c225af9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_G8']/tbody/tr/td/div</value>
      <webElementGuid>3d3ad449-6062-4698-a746-5ec9c23dd608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[2]/following::div[1]</value>
      <webElementGuid>ef6d29e1-eda9-4a4d-ac75-34c58b6b928e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B/O'])[2]/following::div[1]</value>
      <webElementGuid>7d98fd0c-8550-42a5-b992-e407fec1bb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disc %'])[1]/preceding::div[7]</value>
      <webElementGuid>f6af6708-d484-48bc-95fe-042a468eac9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load Details'])[1]/preceding::div[14]</value>
      <webElementGuid>6f1c05f5-1459-4444-8c8f-48f12c0ef101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/table/tbody/tr/td/div</value>
      <webElementGuid>398a0bf3-80ff-48c0-9f58-1a2422f560f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_G7' and (text() = '501 - DEMONSTRATION BRANCH 501' or . = '501 - DEMONSTRATION BRANCH 501')]</value>
      <webElementGuid>a8ab0ba7-ad7c-4b25-8aec-926e828cc881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
