<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Eftpos_Transact</name>
   <tag></tag>
   <elementGuidId>2477cc85-106f-40ef-9faa-25ba36ef5a2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.MediumGridItemSelectedOverDark > div > span.pseudoLink > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[3]/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr >> internal:has-text=&quot;Eftpos Transact$46.50&quot;i >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>62a7b0da-47a0-4e58-b44f-46312ca6e72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://frameworks.dahlsens.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks7/images/custom/menus/checkmark-circle.png</value>
      <webElementGuid>52764c99-6003-46b8-9ba1-159dc7417ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ed7b5c0-bdc6-4a4f-bf93-e2b3bb3b81e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8583a780-938a-4be9-b46b-74aa3e4b8a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1898b25a-4601-4fab-b15e-f96924d155fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_YOtable&quot;)/tbody[1]/tr[2]/td[@class=&quot;MediumGridItemSelectedOverDark&quot;]/div[1]/span[@class=&quot;pseudoLink&quot;]/img[1]</value>
      <webElementGuid>2e35a3ac-55bb-432f-8f0c-349f2f4a2ea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_YOtable']/tbody/tr[2]/td[3]/div/span/img</value>
      <webElementGuid>790d2b0a-f4ca-4b1f-8efc-3718f51c3bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'http://frameworks.dahlsens.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks7/images/custom/menus/checkmark-circle.png')])[2]</value>
      <webElementGuid>6128b108-9218-4272-9e5c-437fb9a7f53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/span/img</value>
      <webElementGuid>1b512f9e-adca-4510-8582-657be12ba1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://frameworks.dahlsens.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks7/images/custom/menus/checkmark-circle.png']</value>
      <webElementGuid>7efe82b6-ddb9-4805-ae8a-3d2ec79e316f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
