<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS4_POS_Account_Credit_Partial_CHC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>dca692c4-1671-459f-934d-590014cffed4</testSuiteGuid>
   <testCaseLink>
      <guid>9de80de2-689b-4434-aa89-78e9c3fc5af7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CHC_Instance/PointofSale_Module/TS2_POS_AccountSale/POS_AccountSale-5006866(TS4)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a7f22d1-b495-48e7-9fbd-64936e6967e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a38c7443-50e4-4a54-a06e-7769fd46e156</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f850088-ac20-449d-9a98-06321b392e14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c553ed8-5180-4330-a681-e3fd4812303c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05189b36-160f-4533-81f5-8e7f043a2ebd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a55f67d-1831-4554-a47c-aab3dcbe6eb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8a920ca-e603-4844-8138-4a1389691ab0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>744928b2-bd76-483b-92a0-c0438b565cc4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CHC_Instance/PointofSale_Module/TS4_POS_AccountCredit_Partial_StockReturn/POS_AccountCredit_Partial_CHC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>157fec99-628a-4fb8-87f8-9b7e4e51ca50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fee56c1b-3a5f-4fa0-a978-e1ca01f9778a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a138b596-b371-4c9c-9e76-4cd267f9e31c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e53fe26e-7242-4a22-8d9d-daf3fdeb8c19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee543d46-9296-44ca-8327-9c850c83e6fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CHC_Instance/PointofSale_Module/TS4_POS_AccountCredit_Partial_StockReturn/POS_AccountCredit_Partial_ValidateRefund_CHC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bee5e70b-983f-45f4-b108-8175f4a2562d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d96f02bb-1c09-4def-892a-36c98f80fda2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdb2cb1a-7cb5-42a5-a972-b732e42e2bc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>772a441d-9532-4b65-aa5a-af28835352ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>473e94be-93a3-40c0-a8d7-b82f6818e771</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CHC_Instance/PointofSale_Module/TS4_POS_AccountCredit_Partial_StockReturn/POS_AccountCredit_Partial_ValidateStock_CHC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c46f2841-1b1a-4127-8dd6-ad04168234cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e05840d9-1859-442d-8c62-72439872ba47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbfeb19b-f13a-4bbd-a437-5615238ea264</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3dad9db2-78da-4d0a-8d9f-3aefb90bbe65</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
