<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tfer SO</name>
   <tag></tag>
   <elementGuidId>7a1c3ad9-e388-48de-a4c5-e2df433f0c2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_165</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'isc_165' and @href = 'javascript:void' and (text() = 'Tfer SO: 26530562' or . = 'Tfer SO: 26530562')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = 'javascript:void' and (contains(text(), 'Tfer SO: ') or contains(., 'Tfer SO: '))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tfer SO: 26530562&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>814cf709-96ff-446a-b136-a460e8786f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_165</value>
      <webElementGuid>55597566-b3b8-49f5-b32b-99c1169afbec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void</value>
      <webElementGuid>b4a2a150-ab30-4ab5-ba61-cb03b4cb5cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>javascript</value>
      <webElementGuid>3e11e5ae-1fb3-4b6b-8066-3e4d689c3ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9692</value>
      <webElementGuid>385f42d5-167d-44f7-9bbc-07cf6869d01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.isc_LinkItem_6) return isc_LinkItem_6.$30i(event);</value>
      <webElementGuid>14312ed3-fe0c-43a9-b99c-351382cda696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>ba015639-52cf-409f-b227-9554881b9446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tfer SO: 26530562</value>
      <webElementGuid>de198dc9-f9a0-4419-a691-6d69a43e2f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_165&quot;)</value>
      <webElementGuid>14c9b8b3-8c4d-4009-b1b2-87b01f8820dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='isc_165']</value>
      <webElementGuid>36257493-fb46-40dd-907c-ebe45869a9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_163']/a</value>
      <webElementGuid>2448b7a2-8c44-42ae-9c65-b63ab9e794d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tfer SO: 26530562')]</value>
      <webElementGuid>3afe9860-32b2-48c1-a6eb-fef1a1f7172e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CDFSrc'])[1]/following::a[1]</value>
      <webElementGuid>bcd8e54f-5d1d-46e0-b050-e70534fad7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volume(m3)'])[1]/following::a[1]</value>
      <webElementGuid>92616e1f-f0bb-4d2a-a3af-9c34492aba69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an item to open'])[1]/preceding::a[1]</value>
      <webElementGuid>c982598e-9e3b-4511-b410-954feaea09ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/preceding::a[1]</value>
      <webElementGuid>bdc571cc-7483-47ec-94aa-7ff4ce2eb22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tfer SO: 26530562']/parent::*</value>
      <webElementGuid>cba5e998-2d8c-4716-a66f-20b516dcfebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void')])[9]</value>
      <webElementGuid>9034a2f2-c9f5-4a38-8116-efbfd29774f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/a</value>
      <webElementGuid>4ac7a43c-992c-4797-bc80-b3f50d478012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'isc_165' and @href = 'javascript:void' and (text() = 'Tfer SO: 26530562' or . = 'Tfer SO: 26530562')]</value>
      <webElementGuid>40b21d8a-fb88-4a23-b4eb-68771b5619c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
