<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_228 - DEMONSTRATION BRANCH 228</name>
   <tag></tag>
   <elementGuidId>77dcb379-8833-4aa3-b2cc-b1cb2d5700b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Q - Gift Card Purchase'])[1]/following::div[32]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(24) > td.pickListCellSelectedDark > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_NCtable >> internal:text=&quot;228 - DEMONSTRATION BRANCH 228&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8538c5a9-98de-48d3-9554-de2af8e10e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>fd3ba73a-99b1-457c-b904-da0010bfed45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>79958070-ed16-4a7e-b439-905ee27a32c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>228 - DEMONSTRATION BRANCH 228</value>
      <webElementGuid>c2edaced-cf74-4210-ae04-9365e9f32997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_NCtable&quot;)/tbody[1]/tr[24]/td[@class=&quot;pickListCellSelectedDark&quot;]/div[1]</value>
      <webElementGuid>06eaa60e-2030-4bc4-a376-c638ed0a7bfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_NCtable']/tbody/tr[24]/td/div</value>
      <webElementGuid>7f95cd45-a16b-471b-b563-92f637a14c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Q - Gift Card Purchase'])[1]/following::div[32]</value>
      <webElementGuid>98f7e7c6-ca6d-416d-97f3-a7964cf3dc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E - Inv to wrong Custome'])[2]/following::div[33]</value>
      <webElementGuid>524d7c7f-f794-4988-b9dc-9b6062136ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/table/tbody/tr[24]/td/div</value>
      <webElementGuid>cb7e8151-a753-4bb2-aaf6-1073214c6f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '228 - DEMONSTRATION BRANCH 228' or . = '228 - DEMONSTRATION BRANCH 228')]</value>
      <webElementGuid>6cff0ae9-cc12-40d7-b71e-fa5400a5615f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
