<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_fw2</name>
   <tag></tag>
   <elementGuidId>c4c93e63-3754-46a8-a604-1e251d357d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;isc_Fmain&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://frameworks.nt.nortruss.com.au:8080/FWDemo/images/frameworks-logo-610.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_F >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dc76774e-dae7-4570-9548-a34c5604946c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://frameworks.nt.nortruss.com.au:8080/FWDemo/images/frameworks-logo-610.png</value>
      <webElementGuid>3930c592-b428-4e92-b84f-db5c02507a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>179</value>
      <webElementGuid>a685c3fe-2d8c-480e-8946-cac57a5eaa53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>8d347a09-fd0b-474e-a983-ce80f57606b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>TEXTTOP</value>
      <webElementGuid>1e057b70-dfad-48a7-a939-c3f3840bb8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isc_Fmain</value>
      <webElementGuid>c13cde15-b1a6-48f3-96a8-c5ec1582af80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5a5b4834-0f02-4c34-b106-e4f6981ffcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>suppress</name>
      <type>Main</type>
      <value>TRUE</value>
      <webElementGuid>758dfbdc-9905-42e3-a7a2-a54a655c545b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e2efa814-65b9-4310-9726-60df14c88962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_F&quot;)/table[1]/tbody[1]/tr[1]/td[1]/img[1]</value>
      <webElementGuid>1c0e200f-0d5f-4419-8177-02de6922afb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='isc_Fmain']</value>
      <webElementGuid>3cc9f436-749c-4717-8268-ea731b5227b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_F']/table/tbody/tr/td/img</value>
      <webElementGuid>b9830d69-23b8-48b7-85bd-c297d1baa38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://frameworks.nt.nortruss.com.au:8080/FWDemo/images/frameworks-logo-610.png')]</value>
      <webElementGuid>166095d7-f007-41ec-a12c-1d9788d29078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/table/tbody/tr/td/img</value>
      <webElementGuid>271229b8-97c4-4d92-98d4-80eb62c1dec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://frameworks.nt.nortruss.com.au:8080/FWDemo/images/frameworks-logo-610.png' and @name = 'isc_Fmain']</value>
      <webElementGuid>e438c961-c90b-4c26-a321-af901284bea2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
