<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Branch</name>
   <tag></tag>
   <elementGuidId>ab171aec-12f0-4413-af93-9261028bb247</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_G8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='isc_G8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Branch&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b02f2cef-00f7-4c56-94d5-55434d8e40a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_SelectItem_5</value>
      <webElementGuid>6fa8b5da-8507-4629-bf73-0f4753f28ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9g</value>
      <webElementGuid>180979fd-7082-437a-9eb5-27702dc82b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_G8</value>
      <webElementGuid>634bfa11-b06a-4e12-ad9d-94abda90da9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formTitle</value>
      <webElementGuid>2eb603ae-ce61-4a64-ad93-22177527fd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>99bf7aba-4691-4242-9f67-9af4163cf934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>c5d49c11-3917-44ca-b389-419793a9d8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Branch</value>
      <webElementGuid>95bd32c1-9598-4293-ad72-388199892018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_G8&quot;)</value>
      <webElementGuid>1be8ecff-93d6-47d9-bf00-203aaf1ac6f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_G8']</value>
      <webElementGuid>6fd6e31a-9470-4aa8-801a-cf1416fac1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_F5']/tbody/tr[3]/td[9]</value>
      <webElementGuid>ed6bab91-f5d8-4336-bc49-fd6aa490459d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B/O'])[2]/following::td[2]</value>
      <webElementGuid>554cca3c-2df1-4a1d-bd38-e72b82359096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Original Docket'])[1]/following::td[8]</value>
      <webElementGuid>7d56ee27-bb76-4334-9629-c27e1c72a59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disc %'])[1]/preceding::td[10]</value>
      <webElementGuid>9d54b7b4-0e37-4998-993a-e1ed2cb5b8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[9]</value>
      <webElementGuid>66351da5-fb17-4f2f-8ef8-fdcf7e654d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_G8' and (text() = 'Branch' or . = 'Branch')]</value>
      <webElementGuid>6a1ed0e5-9b04-4c9d-bd0e-852eb5508d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
