<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Today  7 Days_1_2</name>
   <tag></tag>
   <elementGuidId>dc0bd655-1458-4154-81dd-0ed5334ee575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Today + 7 Days']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_1WZ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Today + 7 Days&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9131d59a-47b2-44dd-9182-aff0455447c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_1WZ</value>
      <webElementGuid>cbe513ba-217e-4531-b96e-cf9377f517bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b2c8ac5b-3d42-4f7f-8ad7-87ecf7988661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today + 7 Days</value>
      <webElementGuid>a1cc272c-e328-462c-a836-c7328f9139c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1WZ&quot;)</value>
      <webElementGuid>d27b8da1-3013-4596-baa8-1a37cea11b56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_1WZ']</value>
      <webElementGuid>2003885f-e8d6-456e-9f99-88a8edea7db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_1X0']/table/tbody/tr/td/div</value>
      <webElementGuid>771f7e82-06df-49f0-bfb9-c1d228630cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tomorrow'])[1]/following::div[2]</value>
      <webElementGuid>a03bcc62-dc86-47fb-890a-7d2be81d1514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/following::div[4]</value>
      <webElementGuid>f1dc4405-764f-4bd1-8504-e84501ab9bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today + 1 Month'])[1]/preceding::div[1]</value>
      <webElementGuid>0dde6aa4-e9f8-437c-afec-8347c3bf5797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Date Confirmation'])[1]/preceding::div[7]</value>
      <webElementGuid>dba32857-6dca-4460-9a1c-a6fe06612fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today + 7 Days']/parent::*</value>
      <webElementGuid>c2220c1e-8e2e-45ab-ab53-74ee93a8c690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/div/div/div[3]/table/tbody/tr/td/div</value>
      <webElementGuid>e8449125-6f1a-4def-85f0-f14f66d8a981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_1WZ' and (text() = 'Today + 7 Days' or . = 'Today + 7 Days')]</value>
      <webElementGuid>f614b322-3f55-459c-8cc0-6d41cfc1e865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
