<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_InformationInformation</name>
   <tag></tag>
   <elementGuidId>be60cb96-a528-42c9-8dd7-77cfd24e99db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_2PM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_2PM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Information&quot;i >> div >> internal:has-text=&quot;InformationInformation&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b894862-36ad-4235-857a-66427bf6d992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_2PM</value>
      <webElementGuid>2e5c201d-0712-4c5e-8162-04113596293e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventproxy</name>
      <type>Main</type>
      <value>isc_Window_1_header</value>
      <webElementGuid>1f48ea1b-dff2-43ef-8cb6-a1ffdb34212e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>windowHeader</value>
      <webElementGuid>e061bd48-0442-4f1e-82c1-74e348ff47de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onscroll</name>
      <type>Main</type>
      <value>return isc_Window_1_header.$lh()</value>
      <webElementGuid>486c19f8-589a-4e41-bf62-503573c173dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c59f7a43-aa39-46d8-9208-f66fdc2af320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  InformationInformation </value>
      <webElementGuid>a3dccfb9-0bc3-4747-bea0-dcbf20079637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_2PM&quot;)</value>
      <webElementGuid>1340d3c4-ad55-4599-9372-e93fcfd2a8fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_2PM']</value>
      <webElementGuid>4f68df53-219a-4312-8c32-90ef6ca670e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_2PJ']/div[4]</value>
      <webElementGuid>f495f80d-ecc5-42f9-ad78-f62b54dc68c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Recommended'])[1]/following::div[3]</value>
      <webElementGuid>947871c0-2ad6-42e3-8bb3-88d330ae3423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[4]/following::div[13]</value>
      <webElementGuid>a7837495-c991-49d5-bf17-13d0168a8a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[4]</value>
      <webElementGuid>d123335e-38a1-40ad-ba72-475397e7e126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_2PM' and (text() = '  InformationInformation ' or . = '  InformationInformation ')]</value>
      <webElementGuid>245b7266-826a-42e9-b124-4322659d0fdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
