<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_SupplierMakita (Australia) Pty. Ltd.C_82f5f9</name>
   <tag></tag>
   <elementGuidId>d8e6538c-011f-4026-a8af-d89bb7b15cc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_1DI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='isc_1DI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>table >> internal:has-text=&quot;SupplierMakita (Australia) Pty. Ltd.CatalogueProduct Description*Unit Of Measure&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
      <webElementGuid>a87802bf-f52b-400c-b5ef-cbdb9a3867bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>b9f9287a-6856-4e8f-ba17-f1ed3b2e90d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_1DI</value>
      <webElementGuid>ac724bb0-985b-489e-a1e7-f6dc65778f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellspacing</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d7cbe8b7-3ec6-4c2e-b68c-5b24a7a865e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellpadding</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>06fe6cec-8590-4f6e-8ba5-8827dfaecd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>72e36f1a-3af3-40b9-8734-8b32adbd01a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SupplierMakita (Australia) Pty. Ltd.CatalogueProduct Description*Unit Of MeasureProduct Group*Tools Power ToolsProduct Sub GroupsCordless Tools/18 VoltSupplier CostWastage %Cost LoadingLoading TypeUnit CostUnit SellGP%Charge GSTLocationLabel QuantityOrder Centrally</value>
      <webElementGuid>a93e3bd6-4aaf-478c-b6ed-fa0a964f0646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1DI&quot;)</value>
      <webElementGuid>ecb62fdc-8402-4912-b687-22eb11fba439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//table[@id='isc_1DI']</value>
      <webElementGuid>565275fb-90b0-47cf-8fec-7c1bb5e8681a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='isc_1DH']/table</value>
      <webElementGuid>3f5a7f69-c66e-4059-b5f9-ef02d6645b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[3]/following::table[1]</value>
      <webElementGuid>947ed825-f89a-47b4-8271-9ad3defaab3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div/div/form/table</value>
      <webElementGuid>dbffa694-f514-409a-a80f-b77c8eb4944c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//table[@id = 'isc_1DI' and (text() = 'SupplierMakita (Australia) Pty. Ltd.CatalogueProduct Description*Unit Of MeasureProduct Group*Tools Power ToolsProduct Sub GroupsCordless Tools/18 VoltSupplier CostWastage %Cost LoadingLoading TypeUnit CostUnit SellGP%Charge GSTLocationLabel QuantityOrder Centrally' or . = 'SupplierMakita (Australia) Pty. Ltd.CatalogueProduct Description*Unit Of MeasureProduct Group*Tools Power ToolsProduct Sub GroupsCordless Tools/18 VoltSupplier CostWastage %Cost LoadingLoading TypeUnit CostUnit SellGP%Charge GSTLocationLabel QuantityOrder Centrally')]</value>
      <webElementGuid>0d5c254c-e133-459f-9a8b-5aee1ff53b07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
