<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_NOT Stocked_isc_2O8</name>
   <tag></tag>
   <elementGuidId>92bf1ff7-85cc-4b45-ba02-6cb848f80c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[6]/div/span/table/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_2O8</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//td[@class = 'selectItemPickerIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_2O8</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c0da0ed4-4360-42e5-90ae-d1999665b070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_2O8</value>
      <webElementGuid>63b12222-0e2a-4961-8fee-09e605f421c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$1906</value>
      <webElementGuid>9811ab45-8709-4337-9f7f-3f001e088d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectItemPickerIcon</value>
      <webElementGuid>ade1281f-d130-4824-af26-c4810b1f2069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_2O8&quot;)</value>
      <webElementGuid>e6970409-2d28-46c7-92a0-991c88c7623f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_2O8']</value>
      <webElementGuid>9a1f04f1-2354-46ec-99c0-486db86f84d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_2O7']/tbody/tr/td[2]</value>
      <webElementGuid>293ca1cb-0dfb-442d-9bee-74b572a9c6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOT Stocked'])[2]/following::td[4]</value>
      <webElementGuid>e648b867-01e7-4cec-92a5-3faae6fdae4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZZ5101228734'])[2]/following::td[6]</value>
      <webElementGuid>2a8324c9-fed0-417e-a96e-33ea0f9e799d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ea'])[2]/preceding::td[4]</value>
      <webElementGuid>3af42943-5ca1-4511-8a09-adeac7a285d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$310.00'])[3]/preceding::td[11]</value>
      <webElementGuid>eb8d2e70-9acb-4ef6-a47b-b95d8b5c8409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/div/span/table/tbody/tr/td[2]</value>
      <webElementGuid>898ba16f-0983-4190-9222-c87ecd5f8fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_2O8']</value>
      <webElementGuid>ee4b848c-e7cd-475a-a264-04c5a1db47ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
