<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Purchase Orders</name>
   <tag></tag>
   <elementGuidId>163ec8a4-1422-4e58-ae7f-4c361f8fc69a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_TreeGrid_0_valueCell14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[15]/td/div/table/tbody/tr/td[(text() = 'Purchase Orders' or . = 'Purchase Orders')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Purchase Orders&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e3d85e62-2b4b-44c4-a826-490acf9c3de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_TreeGrid_0_valueCell14</value>
      <webElementGuid>7ca63b69-31ec-4b86-9fd4-0b425b05ace9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>treeTallCellSelectedOver</value>
      <webElementGuid>9c0e511c-fd50-4c16-84d9-ab205468aa81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchase Orders</value>
      <webElementGuid>0b8bc9b1-c0a0-421e-bd63-eab070a088d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_TreeGrid_0_valueCell14&quot;)</value>
      <webElementGuid>a1c6f0a9-f733-45fe-a764-39aa616d49e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_TreeGrid_0_valueCell14']</value>
      <webElementGuid>9d47c867-c7b1-4306-ac30-39b32e68a7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_7Mtable']/tbody/tr[15]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>1088c106-7dfd-4dc9-8b45-4b1ecca08fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Requisitions'])[1]/following::td[4]</value>
      <webElementGuid>80723eef-bc94-403f-82a1-faeca0ef0cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Processing'])[2]/following::td[8]</value>
      <webElementGuid>7aa301c0-cea4-43de-8f84-782cb1fc02ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock Receipting'])[1]/preceding::td[3]</value>
      <webElementGuid>91304ae6-0db0-486c-a8a2-7da6dd5bada1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Transfers'])[1]/preceding::td[7]</value>
      <webElementGuid>af00485e-d9e8-41ac-a570-172d41e71eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Purchase Orders']/parent::*</value>
      <webElementGuid>b01d7717-581f-4aae-a1c4-b5989e15935e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>d6adf583-1dd4-49cc-8a66-ce5452da19cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_TreeGrid_0_valueCell14' and (text() = 'Purchase Orders' or . = 'Purchase Orders')]</value>
      <webElementGuid>11e5bead-c9cb-4555-8fe1-9aa6385c3390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
