<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tfer SO 401490</name>
   <tag></tag>
   <elementGuidId>7256afa2-1ade-4530-a242-40ccc0db69b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_1BI</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'isc_1BI' and @href = 'javascript:void' and (text() = 'Tfer SO: 401490' or . = 'Tfer SO: 401490')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id = 'isc_1BI' and @href = 'javascript:void' and (text() = 'Tfer SO: 401490' or . = 'Tfer SO: 401490')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tfer SO: 401490&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f03afff2-0d56-4f11-b2e4-055dd3fe623e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_1BI</value>
      <webElementGuid>8444ec7d-2251-422a-9f73-1ebea1094be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void</value>
      <webElementGuid>0c4eb4b0-598b-475d-81af-15c246fad991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>javascript</value>
      <webElementGuid>c670a219-0104-4b3a-9b1c-bc8685c497a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9604</value>
      <webElementGuid>a0eb8d59-04d9-4e58-a554-3d2c319329d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.isc_LinkItem_6) return isc_LinkItem_6.$30i(event);</value>
      <webElementGuid>a3d78fc2-5100-4041-b89b-f0459a457f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>5f5b8381-1f55-49e4-b0a4-0de7f295537e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tfer SO: 401490</value>
      <webElementGuid>f4e468a3-cba7-4a1e-8b2e-a357bd54d94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1BI&quot;)</value>
      <webElementGuid>aa3c6261-ad89-4173-818c-7f35b2d6eef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='isc_1BI']</value>
      <webElementGuid>9e3c8b34-8912-4dfd-9fd3-c8a1aacce004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_1BG']/a</value>
      <webElementGuid>5899fb8e-b4b9-43e4-ab60-bba86f98c24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tfer SO: 401490')]</value>
      <webElementGuid>cd466724-91fb-460f-b30e-801cd5930e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CDFSrc'])[1]/following::a[1]</value>
      <webElementGuid>a1b64e00-bc99-4e20-953e-a4828d3658ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volume(m3)'])[1]/following::a[1]</value>
      <webElementGuid>ce4df9ee-2b3a-4e1a-ace4-c14cafe5ad91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an item to open'])[1]/preceding::a[1]</value>
      <webElementGuid>c744b909-8f33-46b4-a7b1-51836a13242e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/preceding::a[1]</value>
      <webElementGuid>e9b857a3-46c4-4ec3-980d-6ea98b3e2d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tfer SO: 401490']/parent::*</value>
      <webElementGuid>9318439b-1940-486f-ad60-73aced856011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void')])[7]</value>
      <webElementGuid>72e960f4-a70e-4685-b796-e1fd091c8791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/a</value>
      <webElementGuid>ee38a498-c1e8-48bc-a27b-9c06e74aa67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'isc_1BI' and @href = 'javascript:void' and (text() = 'Tfer SO: 401490' or . = 'Tfer SO: 401490')]</value>
      <webElementGuid>3c16a2a3-5a17-45ae-94f5-b9c20f0e8219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
