<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1 - DEMONSTRATION BRANCH 001_1</name>
   <tag></tag>
   <elementGuidId>27754eb1-0a09-4820-a1b3-72e734256356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_1RK</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@$9a = '$9d' and (text() = '1 - DEMONSTRATION BRANCH 001' or . = '1 - DEMONSTRATION BRANCH 001')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_1RK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Branch 1 - DEMONSTRATION BRANCH 001 From Date Show Date Chooser&quot;i] >> internal:role=option</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5eddba73-b0c7-4b26-9b39-4e2fb030003d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_1RK</value>
      <webElementGuid>609b8e6e-17d5-44d9-8a1e-6d6a517fe5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_SelectItem_8</value>
      <webElementGuid>a4998e53-67da-4c2c-9189-c769f6586779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>75baf2fc-4e98-4d04-a15a-a983704a73a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectItemTextFocused</value>
      <webElementGuid>2634ffb2-e57d-4407-8449-05b351b8aaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8267</value>
      <webElementGuid>840ce34a-f948-4b2c-9507-0294a6043473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5e429ed9-6177-4ef8-9698-c73bea766533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 - DEMONSTRATION BRANCH 001</value>
      <webElementGuid>5abcbf5d-a207-482a-b85a-40e8fd190a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1RK&quot;)</value>
      <webElementGuid>9fadb6ad-0253-4dbf-8695-bf9b7feffd69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_1RK']</value>
      <webElementGuid>14a6eb7d-ccc8-48d3-a0e2-714979ab6a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_1RL']/tbody/tr/td/div</value>
      <webElementGuid>d47e9927-4d51-42a1-a5da-0ede8b3aacdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[6]/following::div[1]</value>
      <webElementGuid>4c2f6e94-82cf-4865-9bfd-45aaacb46c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[2]/following::div[13]</value>
      <webElementGuid>ef7a342e-15a8-4f76-b3e9-73c5b8e53374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date'])[1]/preceding::div[1]</value>
      <webElementGuid>c30b10b8-eebe-4d9a-9ebd-8168042c59dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[3]/preceding::div[1]</value>
      <webElementGuid>cf4eeabb-e7b8-4b8f-911c-c5b7fadb665b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/form/table/tbody/tr[2]/td[2]/table/tbody/tr/td/div</value>
      <webElementGuid>f8523479-1634-4b7c-a726-e79745d2125d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_1RK' and (text() = '1 - DEMONSTRATION BRANCH 001' or . = '1 - DEMONSTRATION BRANCH 001')]</value>
      <webElementGuid>04de2761-6dd6-4074-922c-4fc8d6821ac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
