<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Stock Movements</name>
   <tag></tag>
   <elementGuidId>41eb72a8-37b9-4052-9e2b-90c4c331fe79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_10K</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'isc_10K' and (text() = 'Stock Movements')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Stock Movements&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9d0e225a-c40c-4972-96c4-06ccb051b04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_10K</value>
      <webElementGuid>cec2b905-f74b-41f7-be8c-9dbb736919e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>7d895b7c-705f-44a6-874f-e8ec37c023af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stock Movements</value>
      <webElementGuid>44f5542b-f0cc-43fc-8d8d-54279a500130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_10K&quot;)</value>
      <webElementGuid>c3bcf1d1-71c9-4c5d-b35d-252be9e64e29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_10K']</value>
      <webElementGuid>5c68f51f-0a37-4cea-ac44-c52c1c2faeb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_10L']/table/tbody/tr/td/div</value>
      <webElementGuid>c222a470-8046-4b80-8ccf-a9c4fbcd1385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load Price'])[1]/following::div[12]</value>
      <webElementGuid>985e305a-43f5-4cc4-86e4-9e2d6ab150ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Core Status'])[1]/following::div[14]</value>
      <webElementGuid>6409cf50-cee6-4926-aca8-dc85db9c88f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price Enquiry'])[2]/preceding::div[1]</value>
      <webElementGuid>4d1b5ccc-a4cc-409a-901b-d1f4dd8129fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pack Enquiry'])[2]/preceding::div[3]</value>
      <webElementGuid>be29fedb-4222-4523-80fb-fb45f6f82283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>fed4c3e9-3502-4470-8b90-33ebb3804989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_10K' and (text() = 'Stock Movements' or . = 'Stock Movements')]</value>
      <webElementGuid>921d8b97-3405-4d64-a984-834593513413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
