<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Transaction Processing</name>
   <tag></tag>
   <elementGuidId>cc7b6595-64ac-4848-85ae-f081640ad4db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[10]/td/div/table/tbody/tr/td[2]/nobr/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_71icon_9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_71icon_9</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>32f646fc-ab9e-4869-a4ab-97a85ebaf170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_71icon_9</value>
      <webElementGuid>f7a3dc11-c5b9-4b18-aedb-c983de7e1840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_71icon_9&quot;)</value>
      <webElementGuid>8b90a3eb-8821-4a84-99da-2c0b516fde26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='isc_71icon_9']</value>
      <webElementGuid>768bf1c3-a1f0-4b64-ba2c-22bc710443ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_7Btable']/tbody/tr[10]/td/div/table/tbody/tr/td[2]/nobr/span</value>
      <webElementGuid>bea4a697-89d8-4244-b223-d5e9b873e50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/div/table/tbody/tr/td[2]/nobr/span</value>
      <webElementGuid>d57eaa84-cc53-4da8-9be3-2f46134e7979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'isc_71icon_9']</value>
      <webElementGuid>ddc563a2-a71f-4f3c-ad3f-2ece8c0bd2dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
