<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer_idCustX</name>
   <tag></tag>
   <elementGuidId>954ceafa-2cde-45c0-8f87-82e22be7f54f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_F5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'TEXT' and @name = 'idCustX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Customer&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d21156af-224f-4bba-9ac0-0fbc21ae44a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>4044fddc-0f1c-4ede-8d58-882973e4fab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>idCustX</value>
      <webElementGuid>8d6902b8-0b95-4dcc-aa64-14a85cac2ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_F5</value>
      <webElementGuid>e3f1d99f-6827-4bb3-958c-b53b5439ef3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handlenativeevents</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e648dd9b-1dbf-4aa3-a1d0-987bee5e3fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_ComboBoxItem_5</value>
      <webElementGuid>7ed3b77c-5f16-4c18-9580-43a5181991b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9b</value>
      <webElementGuid>808b549e-8329-4a78-b081-48363df11026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eab35fc4-4383-494a-8fe7-f50610fd92d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>isc_ComboBoxItem_5._handleInput()</value>
      <webElementGuid>1016af12-65e5-4fa4-8f57-7ab983da6bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>if (window.isc_ComboBoxItem_5 == null) return;isc_ComboBoxItem_5.$1162()</value>
      <webElementGuid>f3078a8d-8794-4763-8de5-1033157df493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>265d5d6d-04bf-47a5-a7e9-0c02e66c1dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autoSuggestBoxFocused</value>
      <webElementGuid>8eb22166-d122-471c-85e1-232a978ddb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3748</value>
      <webElementGuid>1eacd9ec-0ae6-4da8-bcb5-400266ff1e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_F5&quot;)</value>
      <webElementGuid>8afafaf1-7a20-4ce6-997e-a10f57591600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_F5']</value>
      <webElementGuid>a0e2c825-7434-4aba-ad33-aee8ee5fea1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_LR']/input</value>
      <webElementGuid>c7c3579c-6119-4288-98ba-5b2ce3d166be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/table/tbody/tr[2]/td[2]/div/input</value>
      <webElementGuid>2ce7c380-009c-4baa-98a6-06cfec022eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'idCustX' and @id = 'isc_F5']</value>
      <webElementGuid>c14bf6c2-698a-475e-9d1b-e10761111e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_R4']</value>
      <webElementGuid>3b09e45c-c476-445b-a015-8cea958db912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_SE']/input</value>
      <webElementGuid>14e5f36d-e3b1-4a91-ae4b-7a8aae7eef60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/input</value>
      <webElementGuid>dc4dbe36-2f32-4c13-8230-91855b6bc456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'idCustX' and @id = 'isc_R4']</value>
      <webElementGuid>d1ac793d-8b44-4187-b5e9-3d600a647286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_O0']</value>
      <webElementGuid>b61093f9-9823-4dc8-a89c-5db74c13b247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_UO']/input</value>
      <webElementGuid>198778b5-d975-43fa-be12-e857b826f157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'idCustX' and @id = 'isc_O0']</value>
      <webElementGuid>2597854f-93b0-4765-ba12-4853eeffb782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
