<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Credit Notes</name>
   <tag></tag>
   <elementGuidId>9e114086-b012-49ea-a9cb-f6879974e095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_TreeGrid_0_valueCell4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='isc_TreeGrid_0_valueCell4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Credit Notes&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b16d4026-9287-4bc9-a920-b71b049d4b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_TreeGrid_0_valueCell4</value>
      <webElementGuid>1281518f-dd60-405c-bdcf-60dcf5290144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>treeTallCellSelectedOver</value>
      <webElementGuid>da125614-a6a8-40f1-9fc3-e57b581a8a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Credit Notes</value>
      <webElementGuid>cba9cb78-1476-4888-83ca-824078c1271c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_TreeGrid_0_valueCell4&quot;)</value>
      <webElementGuid>37ad5ae0-541a-4ae3-b402-85e7906a2c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_TreeGrid_0_valueCell4']</value>
      <webElementGuid>a5822b1a-fe4e-4a52-9c62-0da6ceeb1b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_7Btable']/tbody/tr[5]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>11cb5903-5373-477c-b353-a8eba59114c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Orders'])[1]/following::td[4]</value>
      <webElementGuid>a93ff88d-1f99-4e0c-aa3f-a82e63bd6c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Point Of Sale'])[1]/following::td[8]</value>
      <webElementGuid>57eac35a-15c9-47d3-a7f7-ef10a2491330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Picking Dashboard'])[1]/preceding::td[3]</value>
      <webElementGuid>b8f4652a-27d3-412a-b50c-0816142e4225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print Picking Slips'])[1]/preceding::td[7]</value>
      <webElementGuid>849e617f-f1f9-4368-aae8-5343043e58c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Credit Notes']/parent::*</value>
      <webElementGuid>60548b62-9c1d-4e2f-9de8-3e0204714b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>69a370bf-bb5c-495d-8171-62a66f567d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_TreeGrid_0_valueCell4' and (text() = 'Credit Notes' or . = 'Credit Notes')]</value>
      <webElementGuid>a667b6de-da46-4881-946f-46cb98255113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_TreeGrid_0_valueCell5']</value>
      <webElementGuid>06abf0ba-db86-4a7c-8f6b-54aac78dfbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_7Ftable']/tbody/tr[6]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>f4ab566a-64ef-43c6-8097-72e54dcfb033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[1]/following::td[8]</value>
      <webElementGuid>21289cf9-ff96-47bb-a036-bc80e71b0789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>bdc934e7-0d04-4ebd-9e1a-0331e7f3179a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_TreeGrid_0_valueCell5' and (text() = 'Credit Notes' or . = 'Credit Notes')]</value>
      <webElementGuid>a7decf8a-7d9f-4afc-b897-0fba70a714c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
