<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Unknown0.000.00Cash0.000.00Cheque0.000._7ac8bc</name>
   <tag></tag>
   <elementGuidId>525af2fa-8a0c-4bc3-a2a2-db5108815e3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_KP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_KP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_KP</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3b89d8b-a5f3-4bf5-be49-57a9c765c87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_KP</value>
      <webElementGuid>928f85a5-4efc-4009-8105-b567246c6475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventproxy</name>
      <type>Main</type>
      <value>tillRecMain_ttTenderDetail_ListGrid1_body</value>
      <webElementGuid>0ce440c7-f556-4683-9b8d-c3ddba50408b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onscroll</name>
      <type>Main</type>
      <value>return tillRecMain_ttTenderDetail_ListGrid1_body.$lh()</value>
      <webElementGuid>2be4c985-9f47-423a-aa58-214f52d0cc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>isc.EH.handleFocus(tillRecMain_ttTenderDetail_ListGrid1_body,true);</value>
      <webElementGuid>393e5cd8-aad3-4a08-899f-3299c267b104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>if(window.isc)isc.EH.handleBlur(tillRecMain_ttTenderDetail_ListGrid1_body,true);</value>
      <webElementGuid>f66f82b4-69ed-4bae-b5c6-bb40624c42c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2604</value>
      <webElementGuid>75949567-4afa-40c6-ae5e-cd897899d904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unknown$0.000.00Cash$0.000.00Cheque$0.000.00Credit Balance$0.000.00Dahlsens Voucher$0.000.00Bdale Garden Rewards$0.000.00Mitre 10 Gift Card$0.000.00M10 Mighty Rewards$0.000.00M10 Click &amp; Collect$0.000.00Manual Eftpos Machine$0.000.00M10 Vii Gift Card$0.000.00Cards - General$0.000.00Eftpos Transact$31.000.00M10 Gift Card$0.000.00</value>
      <webElementGuid>2c9dcd61-0827-4642-b57f-1afe375a04a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_KP&quot;)</value>
      <webElementGuid>2aaaf71d-6422-4ba1-993c-70176c8a8985</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_KP']</value>
      <webElementGuid>39128fec-a188-4669-921a-c9461d45a4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_K8']/div[2]</value>
      <webElementGuid>35c6ccd0-4713-4245-a6eb-9750d8df17f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$31.00'])[3]/following::div[3]</value>
      <webElementGuid>429f21e0-96bc-41f9-8ef1-54beac89fa25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/following::div[11]</value>
      <webElementGuid>73e5dd93-aeb4-4eae-9eb9-57c8cc90163d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>9ac21216-033a-4b7d-a779-540ba4b23f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_KP' and (text() = 'Unknown$0.000.00Cash$0.000.00Cheque$0.000.00Credit Balance$0.000.00Dahlsens Voucher$0.000.00Bdale Garden Rewards$0.000.00Mitre 10 Gift Card$0.000.00M10 Mighty Rewards$0.000.00M10 Click &amp; Collect$0.000.00Manual Eftpos Machine$0.000.00M10 Vii Gift Card$0.000.00Cards - General$0.000.00Eftpos Transact$31.000.00M10 Gift Card$0.000.00' or . = 'Unknown$0.000.00Cash$0.000.00Cheque$0.000.00Credit Balance$0.000.00Dahlsens Voucher$0.000.00Bdale Garden Rewards$0.000.00Mitre 10 Gift Card$0.000.00M10 Mighty Rewards$0.000.00M10 Click &amp; Collect$0.000.00Manual Eftpos Machine$0.000.00M10 Vii Gift Card$0.000.00Cards - General$0.000.00Eftpos Transact$31.000.00M10 Gift Card$0.000.00')]</value>
      <webElementGuid>9be63fba-7de5-4de8-81a8-c45a6ec198f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
