<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_MenuIconDemo2</name>
   <tag></tag>
   <elementGuidId>70d8b612-2e64-49a6-92a9-e886c6e0ca6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'http://frameworks.dahlsens.com.au:8080/FWDemo2/frameworks/sc/skins/Frameworks7/images/blank.gif')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;isc_Bmain&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_B >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>25c6a031-f6fb-4c3c-af62-830518234f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://frameworks.dahlsens.com.au:8080/FWDemo2/frameworks/sc/skins/Frameworks7/images/blank.gif</value>
      <webElementGuid>3af5a3e1-1641-464c-a388-906b62dbd121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>4619c3e4-08b5-437b-9d9a-0b623da3143e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>0fab60e2-6a60-4d0f-bbd5-fda13315c38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>TEXTTOP</value>
      <webElementGuid>f966107a-821d-44f8-9de7-6b7b30715450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isc_Bmain</value>
      <webElementGuid>d9fbbac5-8164-4966-bbbd-bf19362b991d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>db6d2564-b0c4-4c5e-9665-630b806a24b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>suppress</name>
      <type>Main</type>
      <value>TRUE</value>
      <webElementGuid>4629d206-68ed-473e-896e-a63fe9206a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c85d1a7f-1dd8-494b-a3e4-619a17f67e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_B&quot;)/table[1]/tbody[1]/tr[1]/td[1]/img[1]</value>
      <webElementGuid>12f234d2-8a8c-425e-9dbd-eee63ba71b1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='isc_Bmain']</value>
      <webElementGuid>de20bd43-fba6-4a40-9930-c85f02193b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_B']/table/tbody/tr/td/img</value>
      <webElementGuid>54727c50-aeef-4b69-ad3c-a5fe3bf54d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://frameworks.dahlsens.com.au:8080/FWDemo2/frameworks/sc/skins/Frameworks7/images/blank.gif')]</value>
      <webElementGuid>62e77942-fa72-416e-ba7c-b029db9357be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ca4cb7ac-7b54-4334-b7a1-82f22b514f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://frameworks.dahlsens.com.au:8080/FWDemo2/frameworks/sc/skins/Frameworks7/images/blank.gif' and @name = 'isc_Bmain']</value>
      <webElementGuid>c05160f2-1135-4beb-a00c-f854fadc7c32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
