<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BranchDropdown</name>
   <tag></tag>
   <elementGuidId>98937fed-86d6-4242-8b68-c67b669890be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_GB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Override Stocking Fee'])[1]/preceding::div[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_GB</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f947e164-f7b3-4c53-aebe-75f6e1062e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_GB</value>
      <webElementGuid>461412a9-b36d-474e-a253-f7bca0326d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_SelectItem_5</value>
      <webElementGuid>93376853-5ff4-4138-91e9-c52c9944b0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>dc8a95f6-3609-4e28-9104-a8479229ea97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectItemTextFocused</value>
      <webElementGuid>085d0563-0fbd-469e-ac03-a2b2768962b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4056</value>
      <webElementGuid>d3f5337a-c085-4933-8272-e63496fc97f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>04a86a9b-0cde-4cc1-96c1-58896dfa8d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>228 - DEMONSTRATION BRANCH 228</value>
      <webElementGuid>a39b4211-51db-4709-9778-c0f4e90f5444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_GB&quot;)</value>
      <webElementGuid>c93dc8d3-6a97-4926-8a57-e2e54669bb2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_GB']</value>
      <webElementGuid>91d19fbf-1e0a-43ca-98f3-fd8f62af80f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_GC']/tbody/tr/td/div</value>
      <webElementGuid>a0b87f1d-284b-42e5-86ee-bdd544565352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[2]/following::div[1]</value>
      <webElementGuid>c6d3b225-f795-4d41-b74e-072017a3249c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B/O'])[2]/following::div[1]</value>
      <webElementGuid>b524e628-2709-4c67-b9af-cdd2644ff4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disc %'])[1]/preceding::div[7]</value>
      <webElementGuid>5d531a0b-6cea-40bb-b017-e988ca5f5ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Override Stocking Fee'])[1]/preceding::div[7]</value>
      <webElementGuid>c38a23ad-efa8-43e2-af9c-c2345d1ee40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/table/tbody/tr/td/div</value>
      <webElementGuid>dbb7cda7-b6ab-414c-b475-a3d76ebe056e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_GB' and (text() = '228 - DEMONSTRATION BRANCH 228' or . = '228 - DEMONSTRATION BRANCH 228')]</value>
      <webElementGuid>a7e1653f-e336-40bd-a1c3-37675b1b2e58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
