<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PickQty_lm20</name>
   <tag></tag>
   <elementGuidId>3a86042e-014e-4cf8-beeb-e9da5231c4c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div/div/div/div/div/div/div/table/tbody/tr[2]/td[12]/div[(text() = '0' or . = '0')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_1FItable > tbody > tr:nth-child(2) > td:nth-child(12)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3f537008-b663-4041-8956-a93a0c50b907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>ecab6f78-38d2-45ee-8e8b-233c18f686d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tallCellSelectedOverDark</value>
      <webElementGuid>38bc66d8-37b3-49aa-8ccf-05498afa9a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f1718811-dab2-41a3-b892-fce553ef3a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1FItable&quot;)/tbody[1]/tr[2]/td[@class=&quot;tallCellSelectedOverDark&quot;]</value>
      <webElementGuid>db3cc640-7109-420d-9704-2394ccb67270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_1FItable']/tbody/tr[2]/td[12]</value>
      <webElementGuid>eb35ec48-4886-40ae-a943-0c576caced60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EA'])[2]/following::td[2]</value>
      <webElementGuid>85b13aed-1918-4132-ace1-efaa44f54cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hydrated Lime 20kg'])[1]/following::td[9]</value>
      <webElementGuid>6905db0b-e8df-4c58-bb8e-8d2ff02dba5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Line'])[1]/preceding::td[9]</value>
      <webElementGuid>cd4d54df-2c2c-43da-97b7-0e00e354aa73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code'])[1]/preceding::td[10]</value>
      <webElementGuid>f38c82f6-1a80-4117-97d7-9e84f0d4d8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td[12]</value>
      <webElementGuid>2ddd065d-f90d-49a1-8e3d-c95e0e72167b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '0' or . = '0')]</value>
      <webElementGuid>4f92898f-fd8e-48fb-a9ef-36c9083308c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
