<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SalesOrderLink</name>
   <tag></tag>
   <elementGuidId>149410ae-a633-4100-95fc-08f8ce216c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='if(window.salesOrderView_ttResults_ListGrid1) return salesOrderView_ttResults_ListGrid1.$30i(event,0,0);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;26530562&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9ae9c81-7a51-44d1-803e-6944ed97e648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void</value>
      <webElementGuid>84212f35-6e29-4ec1-9924-c93956338017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>javascript</value>
      <webElementGuid>c885b09e-5c10-402b-9150-8811ae5c6839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.salesOrderView_ttResults_ListGrid1) return salesOrderView_ttResults_ListGrid1.$30i(event,0,0);</value>
      <webElementGuid>0b3994ee-7200-46e2-abf3-3600b89537af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26530562</value>
      <webElementGuid>3cec906b-fb4c-44e2-b189-6f62021de9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_E0table&quot;)/tbody[1]/tr[1]/td[@class=&quot;cellSelectedOver&quot;]/div[1]/a[1]</value>
      <webElementGuid>a4d6e7ec-636e-4d7c-8028-dbe60d30d094</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='if(window.salesOrderView_ttResults_ListGrid1) return salesOrderView_ttResults_ListGrid1.$30i(event,0,0);']</value>
      <webElementGuid>982aefb3-2bb9-4fdb-b575-5efdd7c8528c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_E0table']/tbody/tr/td/div/a</value>
      <webElementGuid>ae06aff6-f23d-4a23-b412-175250d66448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'26530562')]</value>
      <webElementGuid>de367b32-9753-47f6-9748-601d806b986f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$28.93'])[1]/following::a[1]</value>
      <webElementGuid>4033fe0d-7dfe-4a10-afb5-926965c1ad93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JobName'])[1]/following::a[1]</value>
      <webElementGuid>8c4468f1-a0d9-4bfc-9759-20a832c972b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order'])[2]/preceding::a[1]</value>
      <webElementGuid>532f2940-7a12-4c4a-a21f-d15c7b642064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAHLSENS-T/FER A/C-MYRTLEFORD'])[1]/preceding::a[1]</value>
      <webElementGuid>94731706-55b3-46ed-ac31-40d1d5d464a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='26530562']/parent::*</value>
      <webElementGuid>1ce43241-4190-4ab3-b9e8-d0bf9e9a3f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void')]</value>
      <webElementGuid>eedeea6e-cc95-4407-b4a1-b00409a88ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ca1fcf73-ff1c-4eed-9712-937d41aa691f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void' and (text() = '26530562' or . = '26530562')]</value>
      <webElementGuid>28fa0536-1b35-433d-8e1a-6d0de2c742b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
