<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PurchaseOrder_link</name>
   <tag></tag>
   <elementGuidId>6c956994-721d-4b43-9e3b-722728f3e81a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table/tbody/tr[1]/td[1]/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'javascript:void' and @target = 'javascript' and @onclick = 'if(window.purchaseReceiptView_ttResults_ListGrid1) return purchaseReceiptView_ttResults_ListGrid1.$30i(event,0,0);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;53422791&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3b62eca1-6b44-4b6e-b186-a8b2e1353cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void</value>
      <webElementGuid>96f103eb-437a-4194-a602-0263df200ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>javascript</value>
      <webElementGuid>3dad64f8-99b5-4838-9e92-e5bf5e36a3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.purchaseReceiptView_ttResults_ListGrid1) return purchaseReceiptView_ttResults_ListGrid1.$30i(event,0,0);</value>
      <webElementGuid>91b500d1-3b89-42ba-9397-61cb76607325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>53422791</value>
      <webElementGuid>69f759e6-7cba-4bf6-8b64-ebc1708f6703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_I7table&quot;)/tbody[1]/tr[1]/td[@class=&quot;cellSelectedOver&quot;]/div[1]/a[1]</value>
      <webElementGuid>f9f04b9b-3718-46b3-b48b-a3296cf81273</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='if(window.purchaseReceiptView_ttResults_ListGrid1) return purchaseReceiptView_ttResults_ListGrid1.$30i(event,0,0);']</value>
      <webElementGuid>34b13865-40db-4abe-93f4-fe6c1d488f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_I7table']/tbody/tr/td/div/a</value>
      <webElementGuid>080d9b22-68af-4dc3-8258-379f2c4dc49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'53422791')]</value>
      <webElementGuid>2ac10e02-0e75-4de3-94df-2aaf43c1d8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::a[1]</value>
      <webElementGuid>62d57f03-4da5-4fc9-9439-4d185ae34c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SupplierInvoice'])[1]/following::a[1]</value>
      <webElementGuid>811a10e1-1152-42dc-91de-47c9c05aa41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Order'])[1]/preceding::a[1]</value>
      <webElementGuid>80e4dea2-6b1d-480f-88a6-a7d01b448f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAHLSENS TRANSFERS ALBURY'])[1]/preceding::a[1]</value>
      <webElementGuid>5ff8e383-0ebf-4e1b-8acf-a6f0646d418e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='53422791']/parent::*</value>
      <webElementGuid>cf88063f-f4bc-47a8-ab19-a6754b390219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void')]</value>
      <webElementGuid>0f2e285b-99f4-4648-9614-88a9dee460ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>1f68e3d7-8df9-470b-9ff8-bc92834df676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void' and (text() = '53422791' or . = '53422791')]</value>
      <webElementGuid>f4d9f65c-3192-4ddc-8c78-117c4cddd0d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
