<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stock Movements_1</name>
   <tag></tag>
   <elementGuidId>34153995-9435-49c1-aa7b-a55fab3068a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_GI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'isc_GI' and (text() = 'Stock Movements' or . = 'Stock Movements')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'isc_GI' and @unselectable = 'on' and (text() = 'Stock Movements' or . = 'Stock Movements')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Stock Movements&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9a93085-e67b-4ec5-beb2-d0139c2b6e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_GI</value>
      <webElementGuid>5ac4213f-cc44-4f2a-be6b-346595da06f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6e638641-cf69-4be3-89f6-27ce3b624a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stock Movements</value>
      <webElementGuid>f551b2ec-a56e-4424-bce8-741d952462e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_GI&quot;)</value>
      <webElementGuid>fe5a22d7-7538-47a5-97db-2e84171ce2d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_GI']</value>
      <webElementGuid>9ce8a1d4-0073-45b5-ae4a-e021783f4d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_GJ']/table/tbody/tr/td/div</value>
      <webElementGuid>b9df46de-8608-4c49-8511-d640cc5bb1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load Price'])[1]/following::div[12]</value>
      <webElementGuid>144d2ee2-6fbe-4d95-8f0b-c4bede5995c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Core Status'])[1]/following::div[14]</value>
      <webElementGuid>14b96a9a-6045-46cf-a947-edd7ecb1fddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price Enquiry'])[2]/preceding::div[1]</value>
      <webElementGuid>02b85ab5-52b6-4c3d-80ff-a476408daeb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pack Enquiry'])[2]/preceding::div[3]</value>
      <webElementGuid>15f29443-8637-44f1-90df-d04780b07400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>39ab508a-814c-41f9-85f1-4a4c7baca461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_GI' and (text() = 'Stock Movements' or . = 'Stock Movements')]</value>
      <webElementGuid>9e5fa588-e7be-4bae-baec-e048a7e16fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_GH']</value>
      <webElementGuid>a5fef256-0d0a-4e88-ad71-de7ccdf31392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_GI']/table/tbody/tr/td/div</value>
      <webElementGuid>54c269c7-7132-46f4-b4df-35162c3711d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_GH' and (text() = 'Stock Movements' or . = 'Stock Movements')]</value>
      <webElementGuid>ddde495e-9900-41e6-8f93-03482ecbe128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_TB']</value>
      <webElementGuid>ec08d867-81f2-4b71-a453-864bf03baf6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_TC']/table/tbody/tr/td/div</value>
      <webElementGuid>33ca3595-2962-4a24-b6e4-02285a1748e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results'])[1]/following::div[9]</value>
      <webElementGuid>7aacf5ac-c620-43b6-a63d-540dceb73639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search Criteria'])[1]/following::div[11]</value>
      <webElementGuid>6c697e28-f867-431e-aac5-222c5e4da3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pack Enquiry'])[1]/preceding::div[1]</value>
      <webElementGuid>d66a6edb-06db-4868-bb2c-9e709ab03f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price Enquiry'])[1]/preceding::div[3]</value>
      <webElementGuid>29f7b911-4389-4212-b53f-a203b8ce06e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stock Movements']/parent::*</value>
      <webElementGuid>b29ae863-8bc4-4040-9da7-0bfc8862fa7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>a2bfdb54-eaf4-4e11-b3dd-9165650bc18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_TB' and (text() = 'Stock Movements' or . = 'Stock Movements')]</value>
      <webElementGuid>7ec481f5-fcb5-4f17-8984-5f0fd2a53d20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
