<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_E-mail</name>
   <tag></tag>
   <elementGuidId>76b48d5d-5fa4-444a-a053-a7211aec3bf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.pickListCellSelectedDark > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'E-mail' or . = 'E-mail')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_1AMtable >> internal:text=&quot;E-mail&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>00e3c70c-c5d7-4d2d-beb3-e04070b545fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>10eb117a-cd09-4d0c-a445-e01915759a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>070f6060-f8b5-4a8d-9201-6c42aab1f59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-mail</value>
      <webElementGuid>e896fe7d-2480-4265-a19f-82adbe711576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1AMtable&quot;)/tbody[1]/tr[2]/td[@class=&quot;pickListCellSelectedDark&quot;]/div[1]</value>
      <webElementGuid>3f92e530-156a-460c-8d17-6401abf5353d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_1AMtable']/tbody/tr[2]/td/div</value>
      <webElementGuid>8b05633d-786e-4649-a27e-3761fbaf9f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/following::div[1]</value>
      <webElementGuid>872e3556-5408-4c49-b1ac-29e8dd2fb501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::div[10]</value>
      <webElementGuid>5b683842-966a-4950-990b-35cd50b9f577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fax'])[1]/preceding::div[1]</value>
      <webElementGuid>21b0114d-ac9f-48b7-aefd-6f9a12fbb2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pdf'])[1]/preceding::div[2]</value>
      <webElementGuid>fb53e65c-cf87-4c7a-9fbc-73608c02c544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/table/tbody/tr[2]/td/div</value>
      <webElementGuid>13a90d67-e22b-40cf-a90f-d14016a7bca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'E-mail' or . = 'E-mail')]</value>
      <webElementGuid>dcddf3a5-985b-4c44-aecb-b0c07be27ba4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
