<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MultiTill_Reconciliation_CHC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>aea95ae3-a8b6-4d06-97fd-f4aea8691966</testSuiteGuid>
   <testCaseLink>
      <guid>91b93c81-9680-479e-bc50-9cc62e70946e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CHC_Instance/Till Reconciliation/Till Reconciliation_CHC/POS_CashSale</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>571aac75-fcfe-418f-812e-10aa55e023c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a55f67d-1831-4554-a47c-aab3dcbe6eb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8a920ca-e603-4844-8138-4a1389691ab0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d257c5cb-823c-4b10-bc4d-cc27b0536dea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CHC_Instance/Till Reconciliation/Till Reconciliation_CHC/Till_Reconciliation_CashSale</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>71bb632c-a951-46c0-bc52-ef42f33bcff8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CHC_Instance/Till Reconciliation/Multi_TillReconciliation_CHC/MultiTill_Reconciliation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
