<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Reconciled_isc_9J</name>
   <tag></tag>
   <elementGuidId>c05bbe2c-ad05-40b4-99cf-9c876450ab60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Reconciled'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_9J</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Open Locked Reconciled Banked&quot;i] >> div >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90c55972-2148-4369-a5ed-8367e122a8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_9J</value>
      <webElementGuid>c07b4434-1183-40cb-b94d-946fc80c55dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_CheckboxItem_4</value>
      <webElementGuid>aee4018c-db0f-40a3-8d9e-d7ac5740f783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>2d2ecaa9-278c-415c-9ea6-8be1c58ed7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>labelAnchor</value>
      <webElementGuid>aa6e151c-1201-41d1-b230-f60cf8c6687f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2460</value>
      <webElementGuid>0ef13efc-96e8-44d2-9db1-80d77daff31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2a16c207-e054-483b-aadd-5a17a5bf0d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_9J&quot;)</value>
      <webElementGuid>2bf20809-6dcc-42c6-b12b-ee69a12dc3b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_9J']</value>
      <webElementGuid>01298d8b-d5b2-4919-8756-4dbd3f51adf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_9I']/tbody/tr/td/div</value>
      <webElementGuid>d2da6acc-ba97-4d53-b838-0a9b6e4d42bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reconciled'])[1]/following::div[1]</value>
      <webElementGuid>437b3b60-59c3-4053-93be-7b7c128e0823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locked'])[1]/following::div[2]</value>
      <webElementGuid>6b98640b-6cdf-4adf-8270-34943594033e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banked'])[1]/preceding::div[1]</value>
      <webElementGuid>c6082806-c044-457b-8ee0-900045b302c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find'])[1]/preceding::div[2]</value>
      <webElementGuid>301a27df-c4cf-404c-a8ac-b1a2874f06b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/table/tbody/tr/td/div</value>
      <webElementGuid>79bd0eee-ff8c-4fd0-8d5b-51ac7b0d9ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_9J']</value>
      <webElementGuid>b62c4c9a-1136-4f96-adb6-e35583c1fff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
