<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Complete</name>
   <tag></tag>
   <elementGuidId>401050c9-66e8-4b81-bcca-7516050b7c83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[3]/div[3]/div/div/div/div[2]/div/div/div/div/div/div/table/tbody/tr/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_G5</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@unselectable = 'on' and (text() = 'Complete' or . = 'Complete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Complete Till Session&quot;i >> internal:role=button[name=&quot;Complete&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1047711-b821-4f0b-b934-0195fa926117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_G5</value>
      <webElementGuid>4017b44b-bd34-4ed8-8640-6f98572ecd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b3ac59e9-a809-4f77-8c2b-1ea9074c0146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Complete</value>
      <webElementGuid>44e4b392-f54a-4cfc-a878-466dd3df0d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_G5&quot;)</value>
      <webElementGuid>51926ad0-d041-48e1-bf3e-0eeb70c91e08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_G5']</value>
      <webElementGuid>afec9873-abce-4972-bca2-a8730003b5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_G6']/table/tbody/tr/td/div</value>
      <webElementGuid>8ad1f2e1-d2b5-4948-bd1b-9df431ab98fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Variance A/C'])[1]/following::div[3]</value>
      <webElementGuid>469aca18-5572-45b3-a6d3-5c380cd5bb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Variance'])[1]/following::div[3]</value>
      <webElementGuid>3d14540c-4b35-41a2-9306-8b2489401317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete Till Session'])[1]/preceding::div[11]</value>
      <webElementGuid>f695eb44-1af2-4369-b1b3-aa0cb5afd4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete Till Session'])[2]/preceding::div[13]</value>
      <webElementGuid>8dc3d506-2e68-4ca0-86af-044c65eadc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[3]/div/div/div/div[2]/div/div/div/div/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>739bcc00-ea19-4f45-8cd0-e2511c4ed2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_G5' and (text() = 'Complete' or . = 'Complete')]</value>
      <webElementGuid>3dfda24b-36f9-457e-8012-40ddf3f7c913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
