<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QLD - Queensland_1</name>
   <tag></tag>
   <elementGuidId>2bc25594-dd71-47d6-b9b5-8d9c1f26bbd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_XHtable > tbody > tr:nth-of-type(5) > td.pickListCellSelected > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'QLD - Queensland' or . = 'QLD - Queensland')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;QLD - Queensland&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>609a678a-761a-453a-b7c3-777cf5187177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>812b21f0-c1fc-47da-b765-67d9fc9ab5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>08f6fb36-787d-483a-93e9-79af143cebd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QLD - Queensland</value>
      <webElementGuid>a0962eb0-6d0b-4727-a48c-bc20d6523666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_XHtable&quot;)/tbody[1]/tr[5]/td[@class=&quot;pickListCellSelected&quot;]/div[1]</value>
      <webElementGuid>8b4712cc-f654-4c0d-9ef8-fbcd1b27d5e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_XHtable']/tbody/tr[5]/td/div</value>
      <webElementGuid>432c6d12-3528-4bf7-8117-ee5accba3d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NT - Northern Territory'])[1]/following::div[1]</value>
      <webElementGuid>b32d2393-0d83-4337-be3a-6d757e860997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NSW - New South Wales'])[1]/following::div[2]</value>
      <webElementGuid>c5e6234c-3ae8-459b-b5bf-37c2555f79aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SA - South Australia'])[1]/preceding::div[1]</value>
      <webElementGuid>24d89b91-c571-4bfe-bb10-302c350e29b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAS - Tasmania'])[1]/preceding::div[2]</value>
      <webElementGuid>5702d1ff-1f44-4995-bd82-fe8348e05cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QLD - Queensland']/parent::*</value>
      <webElementGuid>ccceaaf0-93b7-4f42-8f57-5a3dc3bb3deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div/div/div/table/tbody/tr[5]/td/div</value>
      <webElementGuid>94cb1233-14f4-4b56-8079-acfc9decafb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'QLD - Queensland' or . = 'QLD - Queensland')]</value>
      <webElementGuid>7970195e-dda8-46f5-ba82-1e2c8bea9515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
