<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HomeSales OrdersSO 220490870</name>
   <tag></tag>
   <elementGuidId>dac8bd43-7dc5-4dc8-880f-ddb64f29a00c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_X</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_X']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;HomeSales OrdersSO 22049087/0&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20696d0e-2d05-4c32-ab27-a1764ae7f795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_X</value>
      <webElementGuid>e2a7f7e1-54b4-4999-b690-71e8d2e00b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventproxy</name>
      <type>Main</type>
      <value>AppTabSet_Main_tabBar</value>
      <webElementGuid>c030703a-db51-466e-bd5c-19932eb18d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabBarTop</value>
      <webElementGuid>d3584e8a-e764-4ac5-a30b-5be08dd820dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onscroll</name>
      <type>Main</type>
      <value>return AppTabSet_Main_tabBar.$lh()</value>
      <webElementGuid>7fd6d4d8-0881-427d-bcfa-344ef2cbf839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tablist</value>
      <webElementGuid>49104c9f-7808-4d30-80cc-bc3f3b5c145c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   HomeSales OrdersSO 22049087/0</value>
      <webElementGuid>bcf86f1f-19cb-4218-8e14-7b09d90b9c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_X&quot;)</value>
      <webElementGuid>32ce3286-e05f-4a9a-8f01-2fdb82a4b638</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_X']</value>
      <webElementGuid>89181852-7460-4dc4-840d-9a4af42c092a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_W']/div</value>
      <webElementGuid>e75b1a5b-7f3f-4f25-80c9-727d0202d89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kino Rafael Manalo (manaki)'])[1]/following::div[3]</value>
      <webElementGuid>336ca31c-aff7-4e36-a279-468019a0a17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Device:'])[1]/following::div[7]</value>
      <webElementGuid>cc05d49e-fc38-4ce1-875c-ef46be75a7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div</value>
      <webElementGuid>71b238b5-5234-4e4f-aba9-5a28f12ceec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_X' and (text() = '   HomeSales OrdersSO 22049087/0' or . = '   HomeSales OrdersSO 22049087/0')]</value>
      <webElementGuid>3b2e8db9-c179-47f5-947a-4b8da93b8f54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
