<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit Sales Order LineEdit Sales Order Line</name>
   <tag></tag>
   <elementGuidId>4e7061e5-9ec3-44f7-9ae1-6b4d21c09e99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_1SF</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_1SF']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=alertdialog >> internal:text=&quot;Edit Sales Order LineEdit Sales Order Line&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>89b7bad8-8382-408b-bcdc-b431a0d7272e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_1SF</value>
      <webElementGuid>d084592f-b78f-4ff1-9c3c-14a8bef3aea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventproxy</name>
      <type>Main</type>
      <value>ErrorDialog_Main_headerLabelLayout</value>
      <webElementGuid>e0a80801-4f7a-4bb4-8365-89d72954223d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>c455132e-415a-41e9-8267-ee0872e7c48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onscroll</name>
      <type>Main</type>
      <value>return ErrorDialog_Main_headerLabelLayout.$lh()</value>
      <webElementGuid>2fc2be88-078d-4e2e-98bc-7126652f4ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Edit Sales Order LineEdit Sales Order Line</value>
      <webElementGuid>a8676a25-4fda-4f27-8702-9fe1626d5e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1SF&quot;)</value>
      <webElementGuid>d655cf23-eca0-41d6-81d5-0cf61c3091af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_1SF']</value>
      <webElementGuid>9deaa1f1-e305-4a73-9504-806fedfe2215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_1SE']/div</value>
      <webElementGuid>17d40400-92e6-46cc-91b6-caa4d3384363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[4]/following::div[3]</value>
      <webElementGuid>6e2ae98a-bf61-40e6-806f-26fadd78f385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/div</value>
      <webElementGuid>4d9cb033-92be-44a3-bf83-56d3ae9c3518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_1SF' and (text() = ' Edit Sales Order LineEdit Sales Order Line' or . = ' Edit Sales Order LineEdit Sales Order Line')]</value>
      <webElementGuid>e4f06991-ea85-494a-adc4-e905e9ff3ee5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
