<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_GP</name>
   <tag></tag>
   <elementGuidId>1b895bca-ad1e-4ef1-b0ec-aee6e0489f78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_1O4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='isc_1O4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sell Price By GP&quot;i >> internal:text=&quot;GP%&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>53f19601-f3a1-49ec-8234-9618a2e320bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_1O4</value>
      <webElementGuid>0756d594-3312-43c8-a8d7-f4a68766d1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>isc_1O3</value>
      <webElementGuid>846b75bc-7d84-4663-b52f-4be71943a15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GP%</value>
      <webElementGuid>ce683e84-f06d-4bdd-8e10-d75919849827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1O4&quot;)</value>
      <webElementGuid>9e26e7e9-8144-4605-a4b1-69a49756b25f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='isc_1O4']</value>
      <webElementGuid>db66588b-c348-4822-9d68-36a31b8594e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='isc_1O2']/nobr/label</value>
      <webElementGuid>40aa3653-57a5-43b7-950a-c9ac8d5d5cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[4]/following::label[1]</value>
      <webElementGuid>0b56ee1a-1d64-479b-8741-3d531360e611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sell Price By GP'])[1]/preceding::label[1]</value>
      <webElementGuid>5f2f3a6e-945b-4a89-bddf-b1e02ff6089c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sell Price By GP'])[2]/preceding::label[1]</value>
      <webElementGuid>f6a561cb-6073-40fe-9976-b97e1b312c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/form/table/tbody/tr[2]/td/nobr/label</value>
      <webElementGuid>e4b4f57c-c7d7-4926-b39d-8de6e10a57c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'isc_1O4' and (text() = 'GP%' or . = 'GP%')]</value>
      <webElementGuid>38b73dc7-b939-4cdb-8898-988449639f34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
