<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Save (S)_1</name>
   <tag></tag>
   <elementGuidId>bc449ad4-cd40-49b2-a247-f3dbb82620cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Y'])[3]/following::td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_1VW > table > tbody > tr > td.buttonPositiveActionDisabled</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//td[@align = 'center' and @nowrap = 'true' and (text() = 'Save (S)' or . = 'Save (S)') and @valign = 'middle' and @onfocus = 'salesOrderComplete_isc_Fluid_0_CRUD_Save.$47()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save (S)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>43720794-a59d-4206-8ee6-7e4be9df31db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonPositiveActionDisabled</value>
      <webElementGuid>ddec78e8-d5cb-4396-a1c3-811f1a9b96ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>3bb1f519-6fac-45fd-941e-e8b94eb655a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nowrap</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>15ca3a15-7519-42af-a26a-5c553dee2e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save (S)</value>
      <webElementGuid>4b82ac13-771b-4a3c-a1a9-82ce6a9e4c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1VW&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;buttonPositiveActionDisabled&quot;]</value>
      <webElementGuid>48b7e2a0-a5d6-4ae0-96e5-e610358baf91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>f2cb5662-b114-44c9-9bee-9f3e92c4e655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>salesOrderComplete_isc_Fluid_0_CRUD_Save.$47()</value>
      <webElementGuid>e21281a8-6393-4e1a-9caf-c7f38979e0dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_1VW']/table/tbody/tr/td</value>
      <webElementGuid>25f519ae-f482-4dee-aacd-827f06a06c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Y'])[3]/following::td[1]</value>
      <webElementGuid>c0d25706-2a93-45a4-ab1c-b32bf312688d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/div/div[4]/div/table/tbody/tr/td</value>
      <webElementGuid>57c6c555-9e1d-456c-9d21-9534c711e5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Save (S)' or . = 'Save (S)')]</value>
      <webElementGuid>b8a99e77-8cc6-4cb3-9984-58f79872481e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_1JX']/table/tbody/tr/td/table/tbody/tr/td[2]</value>
      <webElementGuid>21f4f2f2-25a1-481f-8093-5eeb0110133b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Y'])[3]/following::td[3]</value>
      <webElementGuid>b9350949-4d21-40b3-be71-dafc5d3e54a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/div/div[4]/div/table/tbody/tr/td/table/tbody/tr/td[2]</value>
      <webElementGuid>d7c95599-5b99-46e9-a12f-65c29aff6583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_1D3']/table/tbody/tr/td/table/tbody/tr/td[2]</value>
      <webElementGuid>b93cd9c1-b28a-407a-9471-887ef336e6bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
